module cask

import brew_runtime

// Translated from Homebrew/brew `cask/macos.rb`.
// The original source is retained below until every stub has a typed V body.

// Ruby method `self.system_dir?(dir)` at line 382.
pub fn ruby_macos_l382_d1_self_system_dir(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('self.system_dir?', ...args)
}

// Ruby method `self.undeletable?(path)` at line 387.
pub fn ruby_macos_l387_d2_self_undeletable(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('self.undeletable?', ...args)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: module OS
// 5:   module Mac
// 6:     SYSTEM_DIRS = T.let([
// 7:       "/",
// 8:       "/Applications",
// 9:       "/Applications/Utilities",
// 10:       "/Incompatible Software",
// 11:       "/Library",
// 12:       "/Library/Application Support",
// 13:       "/Library/Audio",
// 14:       "/Library/Caches",
// 15:       "/Library/ColorPickers",
// 16:       "/Library/ColorSync",
// 17:       "/Library/Components",
// 18:       "/Library/Compositions",
// 19:       "/Library/Contextual Menu Items",
// 20:       "/Library/CoreMediaIO",
// 21:       "/Library/Desktop Pictures",
// 22:       "/Library/Developer",
// 23:       "/Library/Dictionaries",
// 24:       "/Library/DirectoryServices",
// 25:       "/Library/Documentation",
// 26:       "/Library/Extensions",
// 27:       "/Library/Filesystems",
// 28:       "/Library/Fonts",
// 29:       "/Library/Frameworks",
// 30:       "/Library/Graphics",
// 31:       "/Library/Image Capture",
// 32:       "/Library/Input Methods",
// 33:       "/Library/Internet Plug-Ins",
// 34:       "/Library/Java",
// 35:       "/Library/Java/Extensions",
// 36:       "/Library/Java/JavaVirtualMachines",
// 37:       "/Library/Keyboard Layouts",
// 38:       "/Library/Keychains",
// 39:       "/Library/LaunchAgents",
// 40:       "/Library/LaunchDaemons",
// 41:       "/Library/Logs",
// 42:       "/Library/Messages",
// 43:       "/Library/Modem Scripts",
// 44:       "/Library/OpenDirectory",
// 45:       "/Library/PDF Services",
// 46:       "/Library/Perl",
// 47:       "/Library/PreferencePanes",
// 48:       "/Library/Preferences",
// 49:       "/Library/Printers",
// 50:       "/Library/PrivilegedHelperTools",
// 51:       "/Library/Python",
// 52:       "/Library/QuickLook",
// 53:       "/Library/QuickTime",
// 54:       "/Library/Receipts",
// 55:       "/Library/Ruby",
// 56:       "/Library/Sandbox",
// 57:       "/Library/Screen Savers",
// 58:       "/Library/ScriptingAdditions",
// 59:       "/Library/Scripts",
// 60:       "/Library/Security",
// 61:       "/Library/Speech",
// 62:       "/Library/Spelling",
// 63:       "/Library/Spotlight",
// 64:       "/Library/StartupItems",
// 65:       "/Library/SystemProfiler",
// 66:       "/Library/Updates",
// 67:       "/Library/User Pictures",
// 68:       "/Library/Video",
// 69:       "/Library/WebServer",
// 70:       "/Library/Widgets",
// 71:       "/Library/iTunes",
// 72:       "/Network",
// 73:       "/System",
// 74:       "/System/Library",
// 75:       "/System/Library/Accessibility",
// 76:       "/System/Library/Accounts",
// 77:       "/System/Library/Address Book Plug-Ins",
// 78:       "/System/Library/Assistant",
// 79:       "/System/Library/Automator",
// 80:       "/System/Library/BridgeSupport",
// 81:       "/System/Library/Caches",
// 82:       "/System/Library/ColorPickers",
// 83:       "/System/Library/ColorSync",
// 84:       "/System/Library/Colors",
// 85:       "/System/Library/Components",
// 86:       "/System/Library/Compositions",
// 87:       "/System/Library/CoreServices",
// 88:       "/System/Library/DTDs",
// 89:       "/System/Library/DirectoryServices",
// 90:       "/System/Library/Displays",
// 91:       "/System/Library/Extensions",
// 92:       "/System/Library/Filesystems",
// 93:       "/System/Library/Filters",
// 94:       "/System/Library/Fonts",
// 95:       "/System/Library/Frameworks",
// 96:       "/System/Library/Graphics",
// 97:       "/System/Library/IdentityServices",
// 98:       "/System/Library/Image Capture",
// 99:       "/System/Library/Input Methods",
// 100:       "/System/Library/InternetAccounts",
// 101:       "/System/Library/Java",
// 102:       "/System/Library/KerberosPlugins",
// 103:       "/System/Library/Keyboard Layouts",
// 104:       "/System/Library/Keychains",
// 105:       "/System/Library/LaunchAgents",
// 106:       "/System/Library/LaunchDaemons",
// 107:       "/System/Library/LinguisticData",
// 108:       "/System/Library/LocationBundles",
// 109:       "/System/Library/LoginPlugins",
// 110:       "/System/Library/Messages",
// 111:       "/System/Library/Metadata",
// 112:       "/System/Library/MonitorPanels",
// 113:       "/System/Library/OpenDirectory",
// 114:       "/System/Library/OpenSSL",
// 115:       "/System/Library/Password Server Filters",
// 116:       "/System/Library/PerformanceMetrics",
// 117:       "/System/Library/Perl",
// 118:       "/System/Library/PreferencePanes",
// 119:       "/System/Library/Printers",
// 120:       "/System/Library/PrivateFrameworks",
// 121:       "/System/Library/QuickLook",
// 122:       "/System/Library/QuickTime",
// 123:       "/System/Library/QuickTimeJava",
// 124:       "/System/Library/Recents",
// 125:       "/System/Library/SDKSettingsPlist",
// 126:       "/System/Library/Sandbox",
// 127:       "/System/Library/Screen Savers",
// 128:       "/System/Library/ScreenReader",
// 129:       "/System/Library/ScriptingAdditions",
// 130:       "/System/Library/ScriptingDefinitions",
// 131:       "/System/Library/Security",
// 132:       "/System/Library/Services",
// 133:       "/System/Library/Sounds",
// 134:       "/System/Library/Speech",
// 135:       "/System/Library/Spelling",
// 136:       "/System/Library/Spotlight",
// 137:       "/System/Library/StartupItems",
// 138:       "/System/Library/SyncServices",
// 139:       "/System/Library/SystemConfiguration",
// 140:       "/System/Library/SystemProfiler",
// 141:       "/System/Library/Tcl",
// 142:       "/System/Library/TextEncodings",
// 143:       "/System/Library/User Template",
// 144:       "/System/Library/UserEventPlugins",
// 145:       "/System/Library/Video",
// 146:       "/System/Library/WidgetResources",
// 147:       "/User Information",
// 148:       "/Users",
// 149:       "/Volumes",
// 150:       "/bin",
// 151:       "/boot",
// 152:       "/cores",
// 153:       "/dev",
// 154:       "/etc",
// 155:       "/etc/X11",
// 156:       "/etc/opt",
// 157:       "/etc/sgml",
// 158:       "/etc/xml",
// 159:       "/home",
// 160:       "/libexec",
// 161:       "/lost+found",
// 162:       "/media",
// 163:       "/mnt",
// 164:       "/net",
// 165:       "/opt",
// 166:       "/private",
// 167:       "/private/etc",
// 168:       "/private/tftpboot",
// 169:       "/private/tmp",
// 170:       "/private/var",
// 171:       "/proc",
// 172:       "/root",
// 173:       "/sbin",
// 174:       "/srv",
// 175:       "/tmp",
// 176:       "/usr",
// 177:       "/usr/X11R6",
// 178:       "/usr/bin",
// 179:       "/usr/etc",
// 180:       "/usr/include",
// 181:       "/usr/lib",
// 182:       "/usr/libexec",
// 183:       "/usr/libexec/cups",
// 184:       "/usr/local",
// 185:       "/usr/local/Cellar",
// 186:       "/usr/local/Frameworks",
// 187:       "/usr/local/Library",
// 188:       "/usr/local/bin",
// 189:       "/usr/local/etc",
// 190:       "/usr/local/include",
// 191:       "/usr/local/lib",
// 192:       "/usr/local/libexec",
// 193:       "/usr/local/opt",
// 194:       "/usr/local/share",
// 195:       "/usr/local/share/man",
// 196:       "/usr/local/share/man/man1",
// 197:       "/usr/local/share/man/man2",
// 198:       "/usr/local/share/man/man3",
// 199:       "/usr/local/share/man/man4",
// 200:       "/usr/local/share/man/man5",
// 201:       "/usr/local/share/man/man6",
// 202:       "/usr/local/share/man/man7",
// 203:       "/usr/local/share/man/man8",
// 204:       "/usr/local/share/man/man9",
// 205:       "/usr/local/share/man/mann",
// 206:       "/usr/local/var",
// 207:       "/usr/local/var/lib",
// 208:       "/usr/local/var/lock",
// 209:       "/usr/local/var/run",
// 210:       "/usr/sbin",
// 211:       "/usr/share",
// 212:       "/usr/share/man",
// 213:       "/usr/share/man/man1",
// 214:       "/usr/share/man/man2",
// 215:       "/usr/share/man/man3",
// 216:       "/usr/share/man/man4",
// 217:       "/usr/share/man/man5",
// 218:       "/usr/share/man/man6",
// 219:       "/usr/share/man/man7",
// 220:       "/usr/share/man/man8",
// 221:       "/usr/share/man/man9",
// 222:       "/usr/share/man/mann",
// 223:       "/usr/src",
// 224:       "/var",
// 225:       "/var/cache",
// 226:       "/var/lib",
// 227:       "/var/lock",
// 228:       "/var/log",
// 229:       "/var/mail",
// 230:       "/var/run",
// 231:       "/var/spool",
// 232:       "/var/spool/mail",
// 233:       "/var/tmp",
// 234:     ]
// 235:                   .to_set { |path| ::Pathname.new(path) }
// 236:                   .freeze, T::Set[::Pathname])
// 237:     private_constant :SYSTEM_DIRS
// 238:
// 239:     # TODO: There should be a way to specify a containing
// 240:     #       directory under which nothing can be deleted.
// 241:     UNDELETABLE_PATHS = T.let([
// 242:       "~/",
// 243:       "~/Applications",
// 244:       "~/Applications/.localized",
// 245:       "~/Desktop",
// 246:       "~/Desktop/.localized",
// 247:       "~/Documents",
// 248:       "~/Documents/.localized",
// 249:       "~/Downloads",
// 250:       "~/Downloads/.localized",
// 251:       "~/Mail",
// 252:       "~/Movies",
// 253:       "~/Movies/.localized",
// 254:       "~/Music",
// 255:       "~/Music/.localized",
// 256:       "~/Music/iTunes",
// 257:       "~/Music/iTunes/iTunes Music",
// 258:       "~/Music/iTunes/Album Artwork",
// 259:       "~/News",
// 260:       "~/Pictures",
// 261:       "~/Pictures/.localized",
// 262:       "~/Pictures/Desktops",
// 263:       "~/Pictures/Photo Booth",
// 264:       "~/Pictures/iChat Icons",
// 265:       "~/Pictures/iPhoto Library",
// 266:       "~/Public",
// 267:       "~/Public/.localized",
// 268:       "~/Sites",
// 269:       "~/Sites/.localized",
// 270:       "~/Library",
// 271:       "~/Library/.localized",
// 272:       "~/Library/Accessibility",
// 273:       "~/Library/Accounts",
// 274:       "~/Library/Address Book Plug-Ins",
// 275:       "~/Library/Application Scripts",
// 276:       "~/Library/Application Support",
// 277:       "~/Library/Application Support/Apple",
// 278:       "~/Library/Application Support/com.apple.AssistiveControl",
// 279:       "~/Library/Application Support/com.apple.QuickLook",
// 280:       "~/Library/Application Support/com.apple.TCC",
// 281:       "~/Library/Assistants",
// 282:       "~/Library/Audio",
// 283:       "~/Library/Automator",
// 284:       "~/Library/Autosave Information",
// 285:       "~/Library/Caches",
// 286:       "~/Library/Calendars",
// 287:       "~/Library/ColorPickers",
// 288:       "~/Library/ColorSync",
// 289:       "~/Library/Colors",
// 290:       "~/Library/Components",
// 291:       "~/Library/Compositions",
// 292:       "~/Library/Containers",
// 293:       "~/Library/Contextual Menu Items",
// 294:       "~/Library/Cookies",
// 295:       "~/Library/DTDs",
// 296:       "~/Library/Desktop Pictures",
// 297:       "~/Library/Developer",
// 298:       "~/Library/Dictionaries",
// 299:       "~/Library/DirectoryServices",
// 300:       "~/Library/Displays",
// 301:       "~/Library/Documentation",
// 302:       "~/Library/Extensions",
// 303:       "~/Library/Favorites",
// 304:       "~/Library/FileSync",
// 305:       "~/Library/Filesystems",
// 306:       "~/Library/Filters",
// 307:       "~/Library/FontCollections",
// 308:       "~/Library/Fonts",
// 309:       "~/Library/Frameworks",
// 310:       "~/Library/GameKit",
// 311:       "~/Library/Graphics",
// 312:       "~/Library/Group Containers",
// 313:       "~/Library/Icons",
// 314:       "~/Library/IdentityServices",
// 315:       "~/Library/Image Capture",
// 316:       "~/Library/Images",
// 317:       "~/Library/Input Methods",
// 318:       "~/Library/Internet Plug-Ins",
// 319:       "~/Library/InternetAccounts",
// 320:       "~/Library/iTunes",
// 321:       "~/Library/KeyBindings",
// 322:       "~/Library/Keyboard Layouts",
// 323:       "~/Library/Keychains",
// 324:       "~/Library/LaunchAgents",
// 325:       "~/Library/LaunchDaemons",
// 326:       "~/Library/LocationBundles",
// 327:       "~/Library/LoginPlugins",
// 328:       "~/Library/Logs",
// 329:       "~/Library/Mail",
// 330:       "~/Library/Mail Downloads",
// 331:       "~/Library/Messages",
// 332:       "~/Library/Metadata",
// 333:       "~/Library/Mobile Documents",
// 334:       "~/Library/MonitorPanels",
// 335:       "~/Library/OpenDirectory",
// 336:       "~/Library/PDF Services",
// 337:       "~/Library/PhonePlugins",
// 338:       "~/Library/Phones",
// 339:       "~/Library/PreferencePanes",
// 340:       "~/Library/Preferences",
// 341:       "~/Library/Printers",
// 342:       "~/Library/PrivateFrameworks",
// 343:       "~/Library/PubSub",
// 344:       "~/Library/QuickLook",
// 345:       "~/Library/QuickTime",
// 346:       "~/Library/Receipts",
// 347:       "~/Library/Recent Servers",
// 348:       "~/Library/Recents",
// 349:       "~/Library/Safari",
// 350:       "~/Library/Saved Application State",
// 351:       "~/Library/Screen Savers",
// 352:       "~/Library/ScreenReader",
// 353:       "~/Library/ScriptingAdditions",
// 354:       "~/Library/ScriptingDefinitions",
// 355:       "~/Library/Scripts",
// 356:       "~/Library/Security",
// 357:       "~/Library/Services",
// 358:       "~/Library/Sounds",
// 359:       "~/Library/Speech",
// 360:       "~/Library/Spelling",
// 361:       "~/Library/Spotlight",
// 362:       "~/Library/StartupItems",
// 363:       "~/Library/StickiesDatabase",
// 364:       "~/Library/Sync Services",
// 365:       "~/Library/SyncServices",
// 366:       "~/Library/SyncedPreferences",
// 367:       "~/Library/TextEncodings",
// 368:       "~/Library/User Pictures",
// 369:       "~/Library/Video",
// 370:       "~/Library/Voices",
// 371:       "~/Library/WebKit",
// 372:       "~/Library/WidgetResources",
// 373:       "~/Library/Widgets",
// 374:       "~/Library/Workflows",
// 375:     ]
// 376:                         .to_set { |path| ::Pathname.new(path.sub(%r{^~(?=(/|$))}, Dir.home)).expand_path }
// 377:                         .union(SYSTEM_DIRS)
// 378:                         .freeze, T::Set[::Pathname])
// 379:     private_constant :UNDELETABLE_PATHS
// 380:
// 381:     sig { params(dir: T.any(::Pathname, String)).returns(T::Boolean) }
// 382:     def self.system_dir?(dir)
// 383:       SYSTEM_DIRS.include?(::Pathname.new(dir).expand_path)
// 384:     end
// 385:
// 386:     sig { params(path: T.any(::Pathname, String)).returns(T::Boolean) }
// 387:     def self.undeletable?(path)
// 388:       UNDELETABLE_PATHS.include?(::Pathname.new(path).expand_path)
// 389:     end
// 390:   end
// 391: end
