module description_cache_store

import brew_runtime

// Translated from Homebrew/brew `description_cache_store/cask_description_cache_store.rb`.
// The original source is retained below until every stub has a typed V body.

// Ruby method `populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)` at line 18.
pub fn ruby_cask_description_cache_store_l18_d1_populate_if_empty(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('populate_if_empty!', ...args)
}

// Ruby method `update_from_report!(report)` at line 31.
pub fn ruby_cask_description_cache_store_l31_d2_update_from_report(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('update_from_report!', ...args)
}

// Ruby method `update_from_cask_tokens!(cask_tokens)` at line 55.
pub fn ruby_cask_description_cache_store_l55_d3_update_from_cask_tokens(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('update_from_cask_tokens!', ...args)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "formula_versions"
// 5:
// 6: #
// 7: # {CaskDescriptionCacheStore} provides methods to fetch and mutate cask descriptions used
// 8: # by the `brew desc` and `brew search` commands.
// 9: #
// 10: class CaskDescriptionCacheStore < DescriptionCacheStore
// 11:   Key = type_member { { fixed: String } }
// 12:   Value = type_member { { fixed: T.anything } }
// 13:
// 14:   # If the database is empty `update!` it with all known casks.
// 15:   #
// 16:   # @return [nil]
// 17:   sig { override.params(eval_all: T::Boolean).void }
// 18:   def populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)
// 19:     return unless eval_all
// 20:     return unless database.empty?
// 21:
// 22:     Cask::Cask.all(eval_all:)
// 23:               .each { |c| update!(c.full_name, [c.name.join(", "), c.desc.presence]) }
// 24:   end
// 25:
// 26:   # Use an update report to update the {CaskDescriptionCacheStore}.
// 27:   #
// 28:   # @param report [Report] an update report generated by cmd/update.rb
// 29:   # @return [nil]
// 30:   sig { override.params(report: ReporterHub).void }
// 31:   def update_from_report!(report)
// 32:     unless Homebrew::EnvConfig.tap_trust_configured?
// 33:       database.clear!
// 34:       return
// 35:     end
// 36:     return populate_if_empty! if database.empty?
// 37:     return if report.empty?
// 38:
// 39:     alterations = T.cast(
// 40:       report.select_formula_or_cask(:AC) +
// 41:       report.select_formula_or_cask(:MC),
// 42:       T::Array[String],
// 43:     )
// 44:     deletions = T.cast(report.select_formula_or_cask(:DC), T::Array[String])
// 45:
// 46:     update_from_cask_tokens!(alterations)
// 47:     delete_from_cask_tokens!(deletions)
// 48:   end
// 49:
// 50:   # Use an array of cask tokens to update the {CaskDescriptionCacheStore}.
// 51:   #
// 52:   # @param cask_tokens [Array] the casks to update
// 53:   # @return [nil]
// 54:   sig { params(cask_tokens: T::Array[String]).void }
// 55:   def update_from_cask_tokens!(cask_tokens)
// 56:     unless Homebrew::EnvConfig.tap_trust_configured?
// 57:       database.clear!
// 58:       return
// 59:     end
// 60:     return populate_if_empty! if database.empty?
// 61:
// 62:     cask_tokens.each do |token|
// 63:       c = Cask::CaskLoader.load(token)
// 64:       update!(c.full_name, [c.name.join(", "), c.desc.presence])
// 65:     rescue Cask::CaskUnavailableError, Homebrew::UntrustedTapError, *FormulaVersions::IGNORED_EXCEPTIONS
// 66:       delete!(token)
// 67:     end
// 68:   end
// 69: end
