module homebrew

import brew_runtime

// Translated from Homebrew/brew `description_cache_store.rb`.
// The original source is retained below until every stub has a typed V body.

// Ruby method `update!(formula_name, description)` at line 22.
pub fn ruby_description_cache_store_l22_d1_update(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('update!', ...args)
}

// Ruby method `delete!(formula_name)` at line 31.
pub fn ruby_description_cache_store_l31_d2_delete(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('delete!', ...args)
}

// Ruby method `populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)` at line 39.
pub fn ruby_description_cache_store_l39_d3_populate_if_empty(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('populate_if_empty!', ...args)
}

// Ruby method `update_from_report!(report)` at line 51.
pub fn ruby_description_cache_store_l51_d4_update_from_report(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('update_from_report!', ...args)
}

// Ruby method `update_from_formula_names!(formula_names)` at line 80.
pub fn ruby_description_cache_store_l80_d5_update_from_formula_names(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('update_from_formula_names!', ...args)
}

// Ruby method `delete_from_formula_names!(formula_names)` at line 99.
pub fn ruby_description_cache_store_l99_d6_delete_from_formula_names(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('delete_from_formula_names!', ...args)
}

// Ruby alias `alias delete_from_cask_tokens! delete_from_formula_names!` at line 104.
pub fn ruby_description_cache_store_l104_d7_delete_from_cask_tokens(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('delete_from_cask_tokens!', ...args)
}

// Ruby method `select(&block)` at line 108.
pub fn ruby_description_cache_store_l108_d8_select(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('select', ...args)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "cache_store"
// 5: require "formula_versions"
// 6:
// 7: #
// 8: # {DescriptionCacheStore} provides methods to fetch and mutate formula descriptions used
// 9: # by the `brew desc` and `brew search` commands.
// 10: #
// 11: class DescriptionCacheStore < CacheStore
// 12:   Key = type_member { { fixed: String } }
// 13:   Value = type_member { { fixed: T.anything } }
// 14:
// 15:   # Inserts a formula description into the cache if it does not exist or
// 16:   # updates the formula description if it does exist.
// 17:   #
// 18:   # @param formula_name [String] the name of the formula to set
// 19:   # @param description  [String] the description from the formula to set
// 20:   # @return [nil]
// 21:   sig { params(formula_name: String, description: T.anything).void }
// 22:   def update!(formula_name, description)
// 23:     database.set(formula_name, description)
// 24:   end
// 25:
// 26:   # Delete the formula description from the {DescriptionCacheStore}.
// 27:   #
// 28:   # @param formula_name [String] the name of the formula to delete
// 29:   # @return [nil]
// 30:   sig { params(formula_name: String).void }
// 31:   def delete!(formula_name)
// 32:     database.delete(formula_name)
// 33:   end
// 34:
// 35:   # If the database is empty `update!` it with all known formulae.
// 36:   #
// 37:   # @return [nil]
// 38:   sig { params(eval_all: T::Boolean).void }
// 39:   def populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)
// 40:     return unless eval_all
// 41:     return unless database.empty?
// 42:
// 43:     Formula.all(eval_all:).each { |f| update!(f.full_name, f.desc) }
// 44:   end
// 45:
// 46:   # Use an update report to update the {DescriptionCacheStore}.
// 47:   #
// 48:   # @param report [Report] an update report generated by cmd/update.rb
// 49:   # @return [nil]
// 50:   sig { params(report: ReporterHub).void }
// 51:   def update_from_report!(report)
// 52:     unless Homebrew::EnvConfig.tap_trust_configured?
// 53:       database.clear!
// 54:       return
// 55:     end
// 56:     return populate_if_empty! if database.empty?
// 57:     return if report.empty?
// 58:
// 59:     renamings = T.cast(report.select_formula_or_cask(:R), T::Array[[String, String]])
// 60:     alterations = T.cast(
// 61:       report.select_formula_or_cask(:A) +
// 62:       report.select_formula_or_cask(:M) +
// 63:       renamings.filter_map(&:last),
// 64:       T::Array[String],
// 65:     )
// 66:     deletions = T.cast(
// 67:       report.select_formula_or_cask(:D) + renamings.filter_map(&:first),
// 68:       T::Array[String],
// 69:     )
// 70:
// 71:     update_from_formula_names!(alterations)
// 72:     delete_from_formula_names!(deletions)
// 73:   end
// 74:
// 75:   # Use an array of formula names to update the {DescriptionCacheStore}.
// 76:   #
// 77:   # @param formula_names [Array] the formulae to update
// 78:   # @return [nil]
// 79:   sig { params(formula_names: T::Array[String]).void }
// 80:   def update_from_formula_names!(formula_names)
// 81:     unless Homebrew::EnvConfig.tap_trust_configured?
// 82:       database.clear!
// 83:       return
// 84:     end
// 85:     return populate_if_empty! if database.empty?
// 86:
// 87:     formula_names.each do |name|
// 88:       update!(name, Formula[name].desc)
// 89:     rescue FormulaUnavailableError, Homebrew::UntrustedTapError, *FormulaVersions::IGNORED_EXCEPTIONS
// 90:       delete!(name)
// 91:     end
// 92:   end
// 93:
// 94:   # Use an array of formula names to delete them from the {DescriptionCacheStore}.
// 95:   #
// 96:   # @param formula_names [Array] the formulae to delete
// 97:   # @return [nil]
// 98:   sig { params(formula_names: T::Array[String]).void }
// 99:   def delete_from_formula_names!(formula_names)
// 100:     return if database.empty?
// 101:
// 102:     formula_names.each { delete!(it) }
// 103:   end
// 104:   alias delete_from_cask_tokens! delete_from_formula_names!
// 105:
// 106:   # `select` from the underlying database.
// 107:   sig { params(block: T.proc.params(arg0: Key, arg1: Value).returns(BasicObject)).returns(T::Hash[Key, Value]) }
// 108:   def select(&block)
// 109:     database.select(&block)
// 110:   end
// 111: end
// 112: require "description_cache_store/cask_description_cache_store"
