module dev_cmd

import ruby
import os

// Translated from Homebrew/brew `test/dev-cmd/typecheck_spec.rb`.
// The original source is retained below until every stub has a typed V body.

const typecheck_spec_rbi_contents = '# typed: true\n\n# This file is autogenerated. Do not edit it by hand.\n# To regenerate, run `brew typecheck --update rubocop`.\n\nclass Parser::Source::Comment\n  include ::RuboCop::Ext::Comment\nend\n\nclass Parser::Source::Range\n  include ::RuboCop::Ext::Range\nend\n\nRuboCop::CLI::STATUS_OFFENSES = T.let(T.unsafe(nil).freeze, Integer)\n\nclass RuboCop::Config\n  include ::RuboCop::PathUtil\n\n  def initialize(hash = T.unsafe(nil)); end\nend\n\nRuboCop::Token = RuboCop::AST::Token\n\nclass RuboCop::Cop::Base\n  include ::RuboCop::Cop::Util\nend\n\nclass RuboCop::Cop::SomeUnusedCop < RuboCop::Cop::Base\n  def on_send(_node); end\nend\n\nmodule RuboCop::Cop::UnusedModule; end\n\nclass CompletelyUnrelated\n  def bananas; end\nend\n\nmodule RuboCop::Version\n  class << self\n    def document_version; end\n  end\nend\n\nVERSION = "x.x.x".freeze\n\nSOME_CONSTANT = "some constant value".freeze\n'

pub struct TypecheckSpecCommand {
pub:
	arguments []string
}

pub fn typecheck_spec_rbi_file(root string) string {
	return os.join_path(root, 'rubocop@x.x.x.rbi')
}

pub fn typecheck_spec_command() TypecheckSpecCommand {
	return TypecheckSpecCommand{}
}

pub fn typecheck_spec_trims_rubocop(root string) !bool {
	os.mkdir_all(root)!
	path := typecheck_spec_rbi_file(root)
	os.write_file(path, typecheck_spec_rbi_contents)!
	old_content := os.read_file(path)!
	result := trim_typecheck_rubocop_rbi(path)!
	new_content := os.read_file(path)!
	os.write_file(path, old_content)!
	return result.found && result.parsed && result.written && new_content.contains('RuboCop::Config')
		&& new_content.contains('RuboCop::Cop::Base') && new_content.contains('Parser::Source')
		&& new_content.contains('VERSION') && new_content.contains('SOME_CONSTANT')
		&& !new_content.contains('SomeUnusedCop') && !new_content.contains('UnusedModule')
		&& !new_content.contains('CompletelyUnrelated')
}

// Ruby let `let(:rbi_file) { Pathname.new("#{TEST_FIXTURE_DIR}/rubocop@x.x.x.rbi") }` at line 11.
pub fn ruby_typecheck_spec_l11_d1_rbi_file(args ...ruby.Value) ruby.Value {
	root := if args.len > 0 { args[0].as_string() } else { os.temp_dir() }
	return ruby.object_value('Pathname', typecheck_spec_rbi_file(root))
}

// Ruby let `let(:typecheck) { described_class.new([]) }` at line 12.
pub fn ruby_typecheck_spec_l12_d2_typecheck(args ...ruby.Value) ruby.Value {
	return ruby.structured_value('Homebrew::DevCmd::Typecheck', 'typecheck', {
		'arguments': typecheck_spec_command().arguments.join(' ')
	})
}

// Ruby it `it "trims RuboCop RBI file to only include allowlisted classes" do` at line 18.
pub fn ruby_typecheck_spec_l18_d3_trims(args ...ruby.Value) ruby.Value {
	root := if args.len > 0 { args[0].as_string() } else { os.temp_dir() }
	return ruby.bool_value(typecheck_spec_trims_rubocop(root) or {
		return ruby.object_value('Error', err.msg())
	})
}

// Original Ruby source (line-for-line):
// 1: # typed: true
// 2: # frozen_string_literal: true
// 3:
// 4: require "cmd/shared_examples/args_parse"
// 5: require "dev-cmd/typecheck"
// 6:
// 7: RSpec.describe Homebrew::DevCmd::Typecheck do
// 8:   it_behaves_like "parseable arguments"
// 9:
// 10:   describe "#trim_rubocop_rbi" do
// 11:     let(:rbi_file) { Pathname.new("#{TEST_FIXTURE_DIR}/rubocop@x.x.x.rbi") }
// 12:     let(:typecheck) { described_class.new([]) }
// 13:
// 14:     before do
// 15:       allow(Dir).to receive(:glob).and_return([rbi_file.to_s])
// 16:     end
// 17:
// 18:     it "trims RuboCop RBI file to only include allowlisted classes" do
// 19:       old_content = rbi_file.read
// 20:
// 21:       typecheck.trim_rubocop_rbi(path: rbi_file.to_s)
// 22:
// 23:       new_content = rbi_file.read
// 24:
// 25:       expect(new_content).to include("RuboCop::Config")
// 26:       expect(new_content).to include("RuboCop::Cop::Base")
// 27:       expect(new_content).to include("Parser::Source")
// 28:       expect(new_content).to include("VERSION")
// 29:       expect(new_content).to include("SOME_CONSTANT")
// 30:       expect(new_content).not_to include("SomeUnusedCop")
// 31:       expect(new_content).not_to include("UnusedModule")
// 32:       expect(new_content).not_to include("CompletelyUnrelated")
// 33:
// 34:       rbi_file.write(old_content)
// 35:     end
// 36:   end
// 37: end
