module rubocops

// Translated from Homebrew/brew `rubocops/all.rb`.
// The original source is retained below until every stub has a typed V body.

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require_relative "../extend/array"
// 5: require_relative "../extend/blank"
// 6: require_relative "api_name_membership"
// 7: require_relative "blank"
// 8: require_relative "compact_blank"
// 9: require_relative "disable_comment"
// 10: require_relative "extend/mutable_constant_exclude_unfreezable"
// 11: require_relative "formula_path_methods"
// 12: require_relative "full_name_split"
// 13: require_relative "install_steps_source_independence"
// 14: require_relative "io_read"
// 15: require_relative "move_to_extend_os"
// 16: require_relative "negate_include"
// 17: require_relative "no_base64"
// 18: require_relative "no_fileutils_rmrf"
// 19: require_relative "no_instance_variable_access_in_tests"
// 20: require_relative "no_send_in_tests"
// 21: require_relative "non_public_api_usage"
// 22: require_relative "presence"
// 23: require_relative "public_api_cookbook"
// 24: require_relative "public_api_documentation"
// 25: require_relative "present"
// 26: require_relative "safe_navigation_with_blank"
// 27: require_relative "shell_command_stub"
// 28: require_relative "shell_commands"
// 29: require_relative "install_bundler_gems"
// 30: require_relative "unreferenced_let"
// 31:
// 32: # formula audit cops
// 33: require_relative "bottle"
// 34: require_relative "caveats"
// 35: require_relative "checksum"
// 36: require_relative "class"
// 37: require_relative "components_order"
// 38: require_relative "components_redundancy"
// 39: require_relative "conflicts"
// 40: require_relative "dependency_order"
// 41: require_relative "deprecate_disable"
// 42: require_relative "no_autobump"
// 43: require_relative "os_depends_on"
// 44: require_relative "desc"
// 45: require_relative "files"
// 46: require_relative "homepage"
// 47: require_relative "install_steps"
// 48: require_relative "keg_only"
// 49: require_relative "lines"
// 50: require_relative "livecheck"
// 51: require_relative "options"
// 52: require_relative "patches"
// 53: require_relative "resource_requires_dependencies"
// 54: require_relative "service"
// 55: require_relative "text"
// 56: require_relative "urls"
// 57: require_relative "uses_from_macos"
// 58: require_relative "version"
// 59: require_relative "zero_zero_zero_zero"
// 60:
// 61: require_relative "rubocop-cask"
