module description_cache_store

import ruby
import homebrew

// Translated from Homebrew/brew `description_cache_store/cask_description_cache_store.rb`.
// The original source is retained below until every stub has a typed V body.
pub struct CaskDescription {
pub:
	full_name   string
	names       []string
	description ?string
}

pub type CaskDescriptionLoader = fn(string) !CaskDescription

fn cask_description_value(cask CaskDescription) ruby.Value {
	description := if value := cask.description {
		ruby.string_value(value)
	} else {
		ruby.Value{ type_name: 'NilClass' }
	}
	return ruby.array_value([
		ruby.string_value(cask.names.join(', ')),
		description,
	])
}

pub fn populate_cask_descriptions_if_empty(mut store homebrew.DescriptionCacheStore,
	eval_all bool, casks []CaskDescription) {
	if !eval_all || !store.database.empty() {
		return
	}
	for cask in casks {
		store.update(cask.full_name, cask_description_value(cask))
	}
}

pub fn update_from_cask_tokens(mut store homebrew.DescriptionCacheStore, tokens []string,
	trust_configured bool, all_casks []CaskDescription, loader CaskDescriptionLoader) {
	if !trust_configured {
		store.database.clear()
		return
	}
	if store.database.empty() {
		populate_cask_descriptions_if_empty(mut store, trust_configured, all_casks)
		return
	}
	for token in tokens {
		cask := loader(token) or {
			store.delete(token)
			continue
		}
		store.update(cask.full_name, cask_description_value(cask))
	}
}

pub fn update_cask_descriptions_from_report(mut store homebrew.DescriptionCacheStore,
	report homebrew.DescriptionReport, trust_configured bool, all_casks []CaskDescription,
	loader CaskDescriptionLoader) {
	if !trust_configured {
		store.database.clear()
		return
	}
	if store.database.empty() {
		populate_cask_descriptions_if_empty(mut store, trust_configured, all_casks)
		return
	}
	if report.empty {
		return
	}
	mut alterations := report.cask_added.clone()
	alterations << report.cask_modified
	update_from_cask_tokens(mut store, alterations, trust_configured, all_casks, loader)
	store.delete_from_formula_names(report.cask_deleted)
}

// Ruby method `populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)` at line 18.
pub fn ruby_cask_description_cache_store_l18_d1_populate_if_empty(mut store homebrew.DescriptionCacheStore,
	eval_all bool, casks []CaskDescription) {
	populate_cask_descriptions_if_empty(mut store, eval_all, casks)
}

// Ruby method `update_from_report!(report)` at line 31.
pub fn ruby_cask_description_cache_store_l31_d2_update_from_report(mut store homebrew.DescriptionCacheStore,
	report homebrew.DescriptionReport, trust_configured bool, all_casks []CaskDescription,
	loader CaskDescriptionLoader) {
	update_cask_descriptions_from_report(mut store, report, trust_configured, all_casks, loader)
}

// Ruby method `update_from_cask_tokens!(cask_tokens)` at line 55.
pub fn ruby_cask_description_cache_store_l55_d3_update_from_cask_tokens(mut store homebrew.DescriptionCacheStore,
	tokens []string, trust_configured bool, all_casks []CaskDescription,
	loader CaskDescriptionLoader) {
	update_from_cask_tokens(mut store, tokens, trust_configured, all_casks, loader)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "formula_versions"
// 5:
// 6: #
// 7: # {CaskDescriptionCacheStore} provides methods to fetch and mutate cask descriptions used
// 8: # by the `brew desc` and `brew search` commands.
// 9: #
// 10: class CaskDescriptionCacheStore < DescriptionCacheStore
// 11:   Key = type_member { { fixed: String } }
// 12:   Value = type_member { { fixed: T.anything } }
// 13:
// 14:   # If the database is empty `update!` it with all known casks.
// 15:   #
// 16:   # @return [nil]
// 17:   sig { override.params(eval_all: T::Boolean).void }
// 18:   def populate_if_empty!(eval_all: Homebrew::EnvConfig.tap_trust_configured?)
// 19:     return unless eval_all
// 20:     return unless database.empty?
// 21:
// 22:     Cask::Cask.all(eval_all:)
// 23:               .each { |c| update!(c.full_name, [c.name.join(", "), c.desc.presence]) }
// 24:   end
// 25:
// 26:   # Use an update report to update the {CaskDescriptionCacheStore}.
// 27:   #
// 28:   # @param report [Report] an update report generated by cmd/update.rb
// 29:   # @return [nil]
// 30:   sig { override.params(report: ReporterHub).void }
// 31:   def update_from_report!(report)
// 32:     unless Homebrew::EnvConfig.tap_trust_configured?
// 33:       database.clear!
// 34:       return
// 35:     end
// 36:     return populate_if_empty! if database.empty?
// 37:     return if report.empty?
// 38:
// 39:     alterations = T.cast(
// 40:       report.select_formula_or_cask(:AC) +
// 41:       report.select_formula_or_cask(:MC),
// 42:       T::Array[String],
// 43:     )
// 44:     deletions = T.cast(report.select_formula_or_cask(:DC), T::Array[String])
// 45:
// 46:     update_from_cask_tokens!(alterations)
// 47:     delete_from_cask_tokens!(deletions)
// 48:   end
// 49:
// 50:   # Use an array of cask tokens to update the {CaskDescriptionCacheStore}.
// 51:   #
// 52:   # @param cask_tokens [Array] the casks to update
// 53:   # @return [nil]
// 54:   sig { params(cask_tokens: T::Array[String]).void }
// 55:   def update_from_cask_tokens!(cask_tokens)
// 56:     unless Homebrew::EnvConfig.tap_trust_configured?
// 57:       database.clear!
// 58:       return
// 59:     end
// 60:     return populate_if_empty! if database.empty?
// 61:
// 62:     cask_tokens.each do |token|
// 63:       c = Cask::CaskLoader.load(token)
// 64:       update!(c.full_name, [c.name.join(", "), c.desc.presence])
// 65:     rescue Cask::CaskUnavailableError, Homebrew::UntrustedTapError, *FormulaVersions::IGNORED_EXCEPTIONS
// 66:       delete!(token)
// 67:     end
// 68:   end
// 69: end
