module dev_cmd

import brew_runtime

// Translated from Homebrew/brew `dev-cmd/pr-pull.rb`.
// The original source is retained below until every stub has a typed V body.

// Ruby method `run` at line 79.
pub fn ruby_pr_pull_l79_d1_run(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('run', ...args)
}

// Ruby method `separate_commit_message(message)` at line 203.
pub fn ruby_pr_pull_l203_d2_separate_commit_message(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('separate_commit_message', ...args)
}

// Ruby method `signoff!(git_repo, pull_request: nil, dry_run: false)` at line 218.
pub fn ruby_pr_pull_l218_d3_signoff(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('signoff!', ...args)
}

// Ruby method `get_package(tap, subject_name, subject_path, content)` at line 248.
pub fn ruby_pr_pull_l248_d4_get_package(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('get_package', ...args)
}

// Ruby method `determine_bump_subject(old_contents, new_contents, subject_path, reason: nil)` at line 269.
pub fn ruby_pr_pull_l269_d5_determine_bump_subject(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('determine_bump_subject', ...args)
}

// Ruby method `reword_package_commit(commit, file, git_repo:, reason: "", verbose: false, resolve: false)` at line 301.
pub fn ruby_pr_pull_l301_d6_reword_package_commit(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('reword_package_commit', ...args)
}

// Ruby method `squash_package_commits(commits, file, git_repo:, reason: "", verbose: false, resolve: false)` at line 333.
pub fn ruby_pr_pull_l333_d7_squash_package_commits(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('squash_package_commits', ...args)
}

// Ruby method `autosquash!(original_commit, tap:, reason: "", verbose: false, resolve: false, cherry_picked: false)` at line 386.
pub fn ruby_pr_pull_l386_d8_autosquash(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('autosquash!', ...args)
}

// Ruby method `check_pull_request_head_sha!(user, repo, pull_request)` at line 457.
pub fn ruby_pr_pull_l457_d9_check_pull_request_head_sha(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('check_pull_request_head_sha!', ...args)
}

// Ruby method `cherry_pick_pr!(user, repo, pull_request, head_sha:, path: ".", commits: nil)` at line 476.
pub fn ruby_pr_pull_l476_d10_cherry_pick_pr(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('cherry_pick_pr!', ...args)
}

// Ruby method `formulae_need_bottles?(tap, original_commit, labels)` at line 499.
pub fn ruby_pr_pull_l499_d11_formulae_need_bottles(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('formulae_need_bottles?', ...args)
}

// Ruby method `changed_packages(tap, original_commit)` at line 510.
pub fn ruby_pr_pull_l510_d12_changed_packages(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('changed_packages', ...args)
}

// Ruby method `pr_check_conflicts(repo, pull_request)` at line 547.
pub fn ruby_pr_pull_l547_d13_pr_check_conflicts(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('pr_check_conflicts', ...args)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "abstract_command"
// 5: require "fileutils"
// 6: require "utils/github"
// 7: require "utils/github/artifacts"
// 8: require "tmpdir"
// 9: require "formula"
// 10:
// 11: module Homebrew
// 12:   module DevCmd
// 13:     class PrPull < AbstractCommand
// 14:       include FileUtils
// 15:
// 16:       cmd_args do
// 17:         description <<~EOS
// 18:           Download and publish bottles and apply the bottle commit from a
// 19:           pull request with artifacts generated by GitHub Actions.
// 20:           Requires write access to the repository.
// 21:         EOS
// 22:         switch "--no-upload",
// 23:                description: "Download the bottles but don't upload them."
// 24:         switch "--no-commit",
// 25:                description: "Do not generate a new commit before uploading."
// 26:         switch "--no-cherry-pick",
// 27:                description: "Do not cherry-pick commits from the pull request branch."
// 28:         switch "-n", "--dry-run",
// 29:                description: "Print what would be done rather than doing it."
// 30:         switch "--clean",
// 31:                description: "Do not amend the commits from pull requests."
// 32:         switch "--keep-old",
// 33:                description: "If the formula specifies a rebuild version, " \
// 34:                             "attempt to preserve its value in the generated DSL."
// 35:         switch "--autosquash",
// 36:                description: "Automatically reformat and reword commits in the pull request to our " \
// 37:                             "preferred format."
// 38:         switch "--branch-okay",
// 39:                description: "Do not warn if pulling to a branch besides the repository default (useful for testing)."
// 40:         switch "--resolve",
// 41:                description: "When a patch fails to apply, leave in progress and allow user to resolve, " \
// 42:                             "instead of aborting."
// 43:         switch "--warn-on-upload-failure",
// 44:                description: "Warn instead of raising an error if the bottle upload fails. " \
// 45:                             "Useful for repairing bottle uploads that previously failed."
// 46:         switch "--retain-bottle-dir",
// 47:                description: "Does not clean up the tmp directory for the bottle so it can be used later."
// 48:         flag   "--committer=",
// 49:                description: "Specify a committer name and email in `git`'s standard author format.",
// 50:                odeprecated: true
// 51:         flag   "--message=",
// 52:                depends_on:  "--autosquash",
// 53:                description: "Message to include when autosquashing revision bumps, deletions and rebuilds."
// 54:         flag   "--artifact-pattern=", "--artifact=",
// 55:                description: "Download artifacts with the specified pattern (default: `bottles{,_*}`)."
// 56:         flag   "--tap=",
// 57:                description: "Target tap repository (default: `homebrew/core`)."
// 58:         flag   "--head-sha=",
// 59:                description: "Expected pull request head commit SHA."
// 60:         flag   "--root-url=",
// 61:                description: "Use the specified <URL> as the root of the bottle's URL instead of Homebrew's default."
// 62:         flag   "--root-url-using=",
// 63:                description: "Use the specified download strategy class for downloading the bottle's URL instead of " \
// 64:                             "Homebrew's default."
// 65:         comma_array "--workflows",
// 66:                     description: "Retrieve artifacts from the specified workflow (default: `tests.yml`). " \
// 67:                                  "Can be a comma-separated list to include multiple workflows."
// 68:         comma_array "--ignore-missing-artifacts",
// 69:                     description: "Comma-separated list of workflows which can be ignored if they have not been run."
// 70:
// 71:         conflicts "--clean", "--autosquash"
// 72:
// 73:         named_args :pull_request, min: 1
// 74:
// 75:         hide_from_man_page!
// 76:       end
// 77:
// 78:       sig { override.void }
// 79:       def run
// 80:         # Needed when extracting the CI artifact.
// 81:         ensure_executable!("unzip", reason: "extracting CI artifacts")
// 82:
// 83:         workflows = args.workflows.presence || ["tests.yml"]
// 84:         artifact_pattern = args.artifact_pattern || "bottles{,_*}"
// 85:         tap = Tap.fetch(args.tap || CoreTap.instance.name)
// 86:         raise TapUnavailableError, tap.name unless tap.installed?
// 87:
// 88:         Utils::Git.set_name_email!(committer: args.committer.blank?)
// 89:         Utils::Git.setup_gpg!
// 90:
// 91:         if (committer = args.committer)
// 92:           committer = Utils.parse_author!(committer)
// 93:           ENV["GIT_COMMITTER_NAME"] = committer[:name]
// 94:           ENV["GIT_COMMITTER_EMAIL"] = committer[:email]
// 95:         end
// 96:
// 97:         args.named.uniq.each do |arg|
// 98:           arg = "#{tap.default_remote}/pull/#{arg}" if arg.to_i.positive?
// 99:           url_match = arg.match HOMEBREW_PULL_OR_COMMIT_URL_REGEX
// 100:           _, user, repo, pr = *url_match
// 101:           odie "Not a GitHub pull request: #{arg}" if !user || !repo || !pr
// 102:
// 103:           git_repo = tap.git_repository
// 104:           if !git_repo.default_origin_branch? && !args.branch_okay? && !args.no_commit? && !args.no_cherry_pick?
// 105:             origin_branch_name = git_repo.origin_branch_name
// 106:             opoo "Current branch is #{git_repo.branch_name}: do you need to pull inside #{origin_branch_name}?"
// 107:           end
// 108:
// 109:           pr_labels = GitHub.pull_request_labels(user, repo, pr)
// 110:           if pr_labels.include?("autosquash") && !args.autosquash?
// 111:             opoo "Pull request is labelled `autosquash`: do you need to pass `--autosquash`?"
// 112:           end
// 113:
// 114:           pull_request_commits = nil
// 115:           head_sha = if (head_sha_arg = args.head_sha.presence)
// 116:             head_sha_arg = head_sha_arg.downcase
// 117:             ohai "Pull request ##{pr} expected head SHA: #{head_sha_arg}"
// 118:             head_sha_arg
// 119:           else
// 120:             pull_request_commits = check_pull_request_head_sha!(user, repo, pr)
// 121:             pull_request_commits.fetch(-1)
// 122:           end
// 123:           pr_check_conflicts("#{user}/#{repo}", pr)
// 124:
// 125:           ohai "Fetching #{tap} pull request ##{pr}"
// 126:           dir = Dir.mktmpdir("pr-pull-#{pr}-", HOMEBREW_TEMP)
// 127:           begin
// 128:             cd dir do
// 129:               current_branch_head = ENV["GITHUB_SHA"] || tap.git_head
// 130:               original_commit = if args.no_cherry_pick?
// 131:                 # TODO: Handle the case where `merge-base` returns multiple commits.
// 132:                 Utils.safe_popen_read("git", "-C", tap.path, "merge-base", "origin/HEAD",
// 133:                                       current_branch_head).strip
// 134:               else
// 135:                 current_branch_head || odie("Failed to get current branch head")
// 136:               end
// 137:               odebug "Pull request merge-base: #{original_commit}"
// 138:
// 139:               unless args.no_commit?
// 140:                 unless args.no_cherry_pick?
// 141:                   cherry_pick_pr!(user, repo, pr, path:    tap.path,
// 142:                                                   commits: pull_request_commits, head_sha:)
// 143:                 end
// 144:                 if args.autosquash? && !args.dry_run?
// 145:                   autosquash!(original_commit, tap:, cherry_picked: !args.no_cherry_pick?,
// 146:                               verbose: args.verbose?, resolve: args.resolve?, reason: args.message)
// 147:                 end
// 148:                 signoff!(git_repo, pull_request: pr, dry_run: args.dry_run?) unless args.clean?
// 149:               end
// 150:
// 151:               unless formulae_need_bottles?(tap, original_commit, pr_labels)
// 152:                 ohai "Skipping artifacts for ##{pr} as the formulae don't need bottles"
// 153:                 next
// 154:               end
// 155:
// 156:               workflows.each do |workflow|
// 157:                 workflow_run = GitHub.get_workflow_run(
// 158:                   user, repo, pr, workflow_id: workflow, artifact_pattern:, head_sha:
// 159:                 )
// 160:                 if args.ignore_missing_artifacts.present? &&
// 161:                    args.ignore_missing_artifacts&.include?(workflow) &&
// 162:                    workflow_run.first.blank?
// 163:                   # Ignore that workflow as it was not executed and we specified
// 164:                   # that we could skip it.
// 165:                   ohai "Ignoring workflow #{workflow} as requested by `--ignore-missing-artifacts`"
// 166:                   next
// 167:                 end
// 168:
// 169:                 ohai "Downloading bottles for workflow: #{workflow}"
// 170:
// 171:                 urls = GitHub.get_artifact_urls(workflow_run)
// 172:                 urls.each { |url| GitHub.download_artifact(url, pr) }
// 173:               end
// 174:
// 175:               next if args.no_upload?
// 176:
// 177:               upload_args = ["pr-upload"]
// 178:               upload_args << "--debug" if args.debug?
// 179:               upload_args << "--verbose" if args.verbose?
// 180:               upload_args << "--no-commit" if args.no_commit?
// 181:               upload_args << "--dry-run" if args.dry_run?
// 182:               upload_args << "--keep-old" if args.keep_old?
// 183:               upload_args << "--warn-on-upload-failure" if args.warn_on_upload_failure?
// 184:               upload_args << "--root-url=#{args.root_url}" if args.root_url
// 185:               upload_args << "--root-url-using=#{args.root_url_using}" if args.root_url_using
// 186:               safe_system HOMEBREW_BREW_FILE, *upload_args
// 187:             end
// 188:           ensure
// 189:             if args.retain_bottle_dir? && GitHub::Actions.env_set?
// 190:               ohai "Bottle files retained at:", dir
// 191:               File.open(ENV.fetch("GITHUB_OUTPUT"), "a") do |f|
// 192:                 f.puts "bottle_path=#{dir}"
// 193:               end
// 194:             else
// 195:               FileUtils.remove_entry dir
// 196:             end
// 197:           end
// 198:         end
// 199:       end
// 200:
// 201:       # Separates a commit message into subject, body and trailers.
// 202:       sig { params(message: String).returns([String, String, String]) }
// 203:       def separate_commit_message(message)
// 204:         first_line = message.lines.first
// 205:         return ["", "", ""] unless first_line
// 206:
// 207:         # Skip the subject and separate lines that look like trailers (e.g. "Co-authored-by")
// 208:         # from lines that look like regular body text.
// 209:         trailers, body = message.lines.drop(1).partition { |s| s.match?(/^[a-z-]+-by:/i) }
// 210:
// 211:         trailers = trailers.uniq.join.strip
// 212:         body = body.join.strip.gsub(/\n{3,}/, "\n\n")
// 213:
// 214:         [first_line.strip, body, trailers]
// 215:       end
// 216:
// 217:       sig { params(git_repo: GitRepository, pull_request: T.nilable(String), dry_run: T::Boolean).void }
// 218:       def signoff!(git_repo, pull_request: nil, dry_run: false)
// 219:         msg = git_repo.commit_message
// 220:         return if msg.blank?
// 221:
// 222:         subject, body, trailers = separate_commit_message(msg)
// 223:
// 224:         if pull_request
// 225:           # This is a tap pull request and approving reviewers should also sign-off.
// 226:           tap = T.must(Tap.from_path(git_repo.pathname))
// 227:           review_trailers = GitHub.repository_approved_reviews(tap.user, tap.full_repository, pull_request).map do |r|
// 228:             "Signed-off-by: #{r["name"]} <#{r["email"]}>"
// 229:           end
// 230:           trailers = trailers.lines.concat(review_trailers).map(&:strip).uniq.join("\n")
// 231:
// 232:           # Append the close message as well, unless the commit body already includes it.
// 233:           close_message = "Closes ##{pull_request}."
// 234:           body.concat("\n\n#{close_message}") unless body.include?(close_message)
// 235:         end
// 236:
// 237:         git_args = Utils::Git.git, "-C", git_repo.pathname, "commit", "--amend", "--signoff", "--allow-empty",
// 238:                    "--quiet", "--message", subject, "--message", body, "--message", trailers
// 239:
// 240:         if dry_run
// 241:           puts(*git_args)
// 242:         else
// 243:           safe_system(*git_args)
// 244:         end
// 245:       end
// 246:
// 247:       sig { params(tap: Tap, subject_name: String, subject_path: Pathname, content: String).returns(T.untyped) }
// 248:       def get_package(tap, subject_name, subject_path, content)
// 249:         if subject_path.to_s.start_with?("#{tap.cask_dir}/")
// 250:           cask = begin
// 251:             Cask::CaskLoader.load(content.dup)
// 252:           rescue Cask::CaskUnavailableError
// 253:             nil
// 254:           end
// 255:           return cask
// 256:         end
// 257:
// 258:         begin
// 259:           Formulary.from_contents(subject_name, subject_path, content, :stable)
// 260:         rescue FormulaUnavailableError
// 261:           nil
// 262:         end
// 263:       end
// 264:
// 265:       sig {
// 266:         params(old_contents: String, new_contents: String, subject_path: T.any(String, Pathname),
// 267:                reason: T.nilable(String)).returns(String)
// 268:       }
// 269:       def determine_bump_subject(old_contents, new_contents, subject_path, reason: nil)
// 270:         subject_path = Pathname(subject_path)
// 271:         tap          = T.must(Tap.from_path(subject_path))
// 272:         subject_name = subject_path.basename.to_s.chomp(".rb")
// 273:         is_cask      = subject_path.to_s.start_with?("#{tap.cask_dir}/")
// 274:         name         = is_cask ? "cask" : "formula"
// 275:
// 276:         new_package = get_package(tap, subject_name, subject_path, new_contents)
// 277:
// 278:         return "#{subject_name}: delete #{reason}".strip if new_package.blank?
// 279:
// 280:         old_package = get_package(tap, subject_name, subject_path, old_contents)
// 281:
// 282:         if old_package.blank?
// 283:           "#{subject_name} #{new_package.version} (new #{name})"
// 284:         elsif old_package.version != new_package.version
// 285:           "#{subject_name} #{new_package.version}"
// 286:         elsif !is_cask && old_package.revision != new_package.revision
// 287:           "#{subject_name}: revision #{reason}".strip
// 288:         elsif is_cask && old_package.sha256 != new_package.sha256
// 289:           "#{subject_name}: checksum update #{reason}".strip
// 290:         else
// 291:           "#{subject_name}: #{reason || "rebuild"}".strip
// 292:         end
// 293:       end
// 294:
// 295:       # Cherry picks a single commit that modifies a single file.
// 296:       # Potentially rewords this commit using {determine_bump_subject}.
// 297:       sig {
// 298:         params(commit: String, file: String, git_repo: GitRepository, reason: T.nilable(String), verbose: T::Boolean,
// 299:                resolve: T::Boolean).void
// 300:       }
// 301:       def reword_package_commit(commit, file, git_repo:, reason: "", verbose: false, resolve: false)
// 302:         package_file = git_repo.pathname / file
// 303:         package_name = package_file.basename.to_s.chomp(".rb")
// 304:
// 305:         odebug "Cherry-picking #{package_file}: #{commit}"
// 306:         Utils::Git.cherry_pick!(git_repo.to_s, commit, verbose:, resolve:)
// 307:
// 308:         old_package = Utils::Git.file_at_commit(git_repo.to_s, file, "HEAD^")
// 309:         new_package = Utils::Git.file_at_commit(git_repo.to_s, file, "HEAD")
// 310:
// 311:         bump_subject = determine_bump_subject(old_package, new_package, package_file, reason:).strip
// 312:         msg = git_repo.commit_message
// 313:         return if msg.blank?
// 314:
// 315:         subject, body, trailers = separate_commit_message(msg)
// 316:
// 317:         if subject != bump_subject && !subject.start_with?("#{package_name}:")
// 318:           safe_system("git", "-C", git_repo.pathname, "commit", "--amend", "-q",
// 319:                       "-m", bump_subject, "-m", subject, "-m", body, "-m", trailers)
// 320:           ohai bump_subject
// 321:         else
// 322:           ohai subject
// 323:         end
// 324:       end
// 325:
// 326:       # Cherry picks multiple commits that each modify a single file.
// 327:       # Words the commit according to {determine_bump_subject} with the body
// 328:       # corresponding to all the original commit messages combined.
// 329:       sig {
// 330:         params(commits: T::Array[String], file: String, git_repo: GitRepository, reason: T.nilable(String),
// 331:                verbose: T::Boolean, resolve: T::Boolean).void
// 332:       }
// 333:       def squash_package_commits(commits, file, git_repo:, reason: "", verbose: false, resolve: false)
// 334:         odebug "Squashing #{file}: #{commits.join " "}"
// 335:
// 336:         # Format commit messages into something similar to `git fmt-merge-message`.
// 337:         # * subject 1
// 338:         # * subject 2
// 339:         #   optional body
// 340:         # * subject 3
// 341:         messages = []
// 342:         trailers = []
// 343:         commits.each do |commit|
// 344:           msg = git_repo.commit_message(commit)
// 345:           next if msg.blank?
// 346:
// 347:           subject, body, trailer = separate_commit_message(msg)
// 348:           body = body.lines.map { |line| "  #{line.strip}" }.join("\n")
// 349:           messages << "* #{subject}\n#{body}".strip
// 350:           trailers << trailer
// 351:         end
// 352:
// 353:         # Get the set of authors in this series.
// 354:         authors = Utils.safe_popen_read("git", "-C", git_repo.pathname, "show",
// 355:                                         "--no-patch", "--pretty=%an <%ae>", *commits).lines.map(&:strip).uniq.compact
// 356:
// 357:         # Get the author and date of the first commit of this series, which we use for the squashed commit.
// 358:         original_author = authors.shift
// 359:         original_date = Utils.safe_popen_read "git", "-C", git_repo.pathname, "show", "--no-patch", "--pretty=%ad",
// 360:                                               commits.first
// 361:
// 362:         # Generate trailers for coauthors and combine them with the existing trailers.
// 363:         co_author_trailers = authors.map { |au| "Co-authored-by: #{au}" }
// 364:         trailers = [trailers + co_author_trailers].flatten.uniq.compact
// 365:
// 366:         # Apply the patch series but don't commit anything yet.
// 367:         Utils::Git.cherry_pick!(git_repo.pathname, "--no-commit", *commits, verbose:, resolve:)
// 368:
// 369:         # Determine the bump subject by comparing the original state of the tree to its current state.
// 370:         package_file = git_repo.pathname / file
// 371:         old_package = Utils::Git.file_at_commit(git_repo.pathname, file, "#{commits.first}^")
// 372:         new_package = package_file.read
// 373:         bump_subject = determine_bump_subject(old_package, new_package, package_file, reason:)
// 374:
// 375:         # Commit with the new subject, body and trailers.
// 376:         safe_system("git", "-C", git_repo.pathname, "commit", "--quiet",
// 377:                     "-m", bump_subject, "-m", messages.join("\n"), "-m", trailers.join("\n"),
// 378:                     "--author", original_author, "--date", original_date, "--", file)
// 379:         ohai bump_subject
// 380:       end
// 381:
// 382:       sig {
// 383:         params(original_commit: String, tap: Tap, reason: T.nilable(String), verbose: T::Boolean, resolve: T::Boolean,
// 384:                cherry_picked: T::Boolean).void
// 385:       }
// 386:       def autosquash!(original_commit, tap:, reason: "", verbose: false, resolve: false, cherry_picked: false)
// 387:         git_repo = tap.git_repository
// 388:
// 389:         commits = Utils.safe_popen_read("git", "-C", tap.path, "rev-list",
// 390:                                         "--reverse", "#{original_commit}..HEAD").lines.map(&:strip)
// 391:
// 392:         # Generate a bidirectional mapping of commits <=> formula/cask files.
// 393:         files_to_commits = T.let({}, T::Hash[String, T::Array[String]])
// 394:         commits_to_files = commits.to_h do |commit|
// 395:           files = Utils.safe_popen_read("git", "-C", tap.path, "diff-tree", "--diff-filter=AMD",
// 396:                                         "-r", "--name-only", "#{commit}^", commit).lines.map(&:strip)
// 397:           files.each do |file|
// 398:             files_to_commits[file] ||= []
// 399:             files_to_commits.fetch(file) << commit
// 400:             tap_file = (tap.path/file).to_s
// 401:             if tap_file.start_with?("#{tap.formula_dir}/", "#{tap.cask_dir}/") &&
// 402:                File.extname(file) == ".rb"
// 403:               next
// 404:             end
// 405:
// 406:             odie <<~EOS
// 407:               Autosquash can only squash commits that modify formula or cask files.
// 408:                 File:   #{file}
// 409:                 Commit: #{commit}
// 410:             EOS
// 411:           end
// 412:           [commit, files]
// 413:         end
// 414:
// 415:         # Reset to state before cherry-picking.
// 416:         safe_system "git", "-C", tap.path, "reset", "--hard", original_commit
// 417:
// 418:         # Iterate over every commit in the pull request series, but if we have to squash
// 419:         # multiple commits into one, ensure that we skip over commits we've already squashed.
// 420:         processed_commits = T.let([], T::Array[String])
// 421:         commits.each do |commit|
// 422:           next if processed_commits.include? commit
// 423:
// 424:           files = commits_to_files.fetch(commit)
// 425:           if files.length == 1 && files_to_commits.fetch(files.fetch(0)).length == 1
// 426:             # If there's a 1:1 mapping of commits to files, just cherry pick and (maybe) reword.
// 427:             reword_package_commit(
// 428:               commit, files.fetch(0), git_repo:, reason:, verbose:, resolve:
// 429:             )
// 430:             processed_commits << commit
// 431:           elsif files.length == 1 && files_to_commits.fetch(files.fetch(0)).length > 1
// 432:             # If multiple commits modify a single file, squash them down into a single commit.
// 433:             file = files.fetch(0)
// 434:             commits = files_to_commits.fetch(file)
// 435:             squash_package_commits(commits, file, git_repo:, reason:, verbose:, resolve:)
// 436:             processed_commits += commits
// 437:           else
// 438:             # We can't split commits (yet) so just raise an error.
// 439:             odie <<~EOS
// 440:               Autosquash can't split commits that modify multiple files.
// 441:                 Commit: #{commit}
// 442:                 Files:  #{files.join " "}
// 443:             EOS
// 444:           end
// 445:         end
// 446:       rescue
// 447:         original_head = git_repo&.head_ref
// 448:         return if original_head.nil?
// 449:
// 450:         opoo "Autosquash encountered an error; resetting to original state at #{original_head}"
// 451:         system "git", "-C", tap.path.to_s, "reset", "--hard", original_head
// 452:         system "git", "-C", tap.path.to_s, "cherry-pick", "--abort" if cherry_picked
// 453:         raise
// 454:       end
// 455:
// 456:       sig { params(user: String, repo: String, pull_request: String).returns(T::Array[String]) }
// 457:       def check_pull_request_head_sha!(user, repo, pull_request)
// 458:         commits = GitHub.pull_request_commits(user, repo, pull_request)
// 459:         pull_request_head_sha = commits.fetch(-1)
// 460:         ohai "Pull request ##{pull_request} head SHA: #{pull_request_head_sha}"
// 461:         commits
// 462:       end
// 463:
// 464:       private
// 465:
// 466:       sig {
// 467:         params(
// 468:           user:         String,
// 469:           repo:         String,
// 470:           pull_request: String,
// 471:           head_sha:     String,
// 472:           path:         T.any(String, Pathname),
// 473:           commits:      T.nilable(T::Array[String]),
// 474:         ).void
// 475:       }
// 476:       def cherry_pick_pr!(user, repo, pull_request, head_sha:, path: ".", commits: nil)
// 477:         if args.dry_run?
// 478:           puts <<~EOS
// 479:             git fetch --force origin +refs/pull/#{pull_request}/head
// 480:             git merge-base HEAD FETCH_HEAD
// 481:             git cherry-pick --ff --allow-empty $merge_base..FETCH_HEAD
// 482:           EOS
// 483:           return
// 484:         end
// 485:
// 486:         commits ||= GitHub.pull_request_commits(user, repo, pull_request)
// 487:         pull_request_head_sha = commits.fetch(-1).downcase
// 488:         if pull_request_head_sha != head_sha
// 489:           odie "Pull request ##{pull_request} is at #{pull_request_head_sha} but expected #{head_sha}."
// 490:         end
// 491:
// 492:         safe_system "git", "-C", path, "fetch", "--quiet", "--force", "origin", commits.last
// 493:         ohai "Using #{commits.count} commit#{"s" if commits.count != 1} from ##{pull_request}"
// 494:         Utils::Git.cherry_pick!(path, "--ff", "--allow-empty", *commits, verbose: args.verbose?,
// 495:                                                                          resolve: args.resolve?)
// 496:       end
// 497:
// 498:       sig { params(tap: Tap, original_commit: String, labels: T::Array[String]).returns(T::Boolean) }
// 499:       def formulae_need_bottles?(tap, original_commit, labels)
// 500:         return false if args.dry_run?
// 501:
// 502:         return false if labels.include?("CI-syntax-only") || labels.include?("CI-no-bottles")
// 503:
// 504:         changed_packages(tap, original_commit).any? do |f|
// 505:           !f.instance_of?(Cask::Cask)
// 506:         end
// 507:       end
// 508:
// 509:       sig { params(tap: Tap, original_commit: String).returns(T::Array[T.any(Formula, Cask::Cask)]) }
// 510:       def changed_packages(tap, original_commit)
// 511:         formulae = Utils.popen_read("git", "-C", tap.path, "diff-tree",
// 512:                                     "-r", "--name-only", "--diff-filter=AM",
// 513:                                     original_commit, "HEAD", "--", tap.formula_dir)
// 514:                         .lines
// 515:                         .filter_map do |line|
// 516:           next unless line.end_with? ".rb\n"
// 517:
// 518:           name = "#{tap.name}/#{File.basename(line.chomp, ".rb")}"
// 519:           if Homebrew::EnvConfig.disable_load_formula?
// 520:             opoo "Can't check if updated bottles are necessary as `$HOMEBREW_DISABLE_LOAD_FORMULA` is set!"
// 521:             break []
// 522:           end
// 523:           begin
// 524:             Formulary.resolve(name)
// 525:           rescue FormulaUnavailableError
// 526:             nil
// 527:           end
// 528:         end
// 529:         casks = Utils.popen_read("git", "-C", tap.path, "diff-tree",
// 530:                                  "-r", "--name-only", "--diff-filter=AM",
// 531:                                  original_commit, "HEAD", "--", tap.cask_dir)
// 532:                      .lines
// 533:                      .filter_map do |line|
// 534:           next unless line.end_with? ".rb\n"
// 535:
// 536:           name = "#{tap.name}/#{File.basename(line.chomp, ".rb")}"
// 537:           begin
// 538:             Cask::CaskLoader.load(name)
// 539:           rescue Cask::CaskUnavailableError
// 540:             nil
// 541:           end
// 542:         end
// 543:         formulae + casks
// 544:       end
// 545:
// 546:       sig { params(repo: String, pull_request: String).void }
// 547:       def pr_check_conflicts(repo, pull_request)
// 548:         long_build_pr_files = GitHub.issues(
// 549:           repo:, state: "open", labels: "no long build conflict",
// 550:         ).each_with_object({}) do |long_build_pr, hash|
// 551:           next unless long_build_pr.key?("pull_request")
// 552:
// 553:           number = long_build_pr["number"]
// 554:           next if number == pull_request.to_i
// 555:
// 556:           GitHub.get_pull_request_changed_files(repo, number).each do |file|
// 557:             key = file["filename"]
// 558:             hash[key] ||= []
// 559:             hash[key] << number
// 560:           end
// 561:         end
// 562:
// 563:         return if long_build_pr_files.blank?
// 564:
// 565:         this_pr_files = GitHub.get_pull_request_changed_files(repo, pull_request)
// 566:
// 567:         conflicts = this_pr_files.each_with_object({}) do |file, hash|
// 568:           filename = file["filename"]
// 569:           next unless long_build_pr_files.key?(filename)
// 570:
// 571:           long_build_pr_files[filename].each do |pr_number|
// 572:             key = "#{repo}/pull/#{pr_number}"
// 573:             hash[key] ||= []
// 574:             hash[key] << filename
// 575:           end
// 576:         end
// 577:
// 578:         return if conflicts.blank?
// 579:
// 580:         # Raise an error, display the conflicting PR. For example:
// 581:         # Error: You are trying to merge a pull request that conflicts with a long running build in:
// 582:         # {
// 583:         #   "homebrew-core/pull/98809": [
// 584:         #    "Formula/icu4c.rb",
// 585:         #    "Formula/node@10.rb"
// 586:         #   ]
// 587:         # }
// 588:         odie <<~EOS
// 589:           You are trying to merge a pull request that conflicts with a long running build in:
// 590:           #{JSON.pretty_generate(conflicts)}
// 591:         EOS
// 592:       end
// 593:     end
// 594:   end
// 595: end
