module dev_cmd

import brew_runtime
import os

// Translated from Homebrew/brew `dev-cmd/typecheck.rb`.
// The original source is retained below until every stub has a typed V body.

const typecheck_rubocop_allowlist = [
	'CopHelper',
	'Parser::Source',
	'RuboCop::AST::Node',
	'RuboCop::AST::NodePattern',
	'RuboCop::AST::ProcessedSource',
	'RuboCop::CLI',
	'RuboCop::Config',
	'RuboCop::Cop::AllowedPattern',
	'RuboCop::Cop::AllowedMethods',
	'RuboCop::Cop::AutoCorrector',
	'RuboCop::Cop::AutocorrectLogic',
	'RuboCop::Cop::Base',
	'RuboCop::Cop::CommentsHelp',
	'RuboCop::Cop::ConfigurableFormatting',
	'RuboCop::Cop::ConfigurableNaming',
	'RuboCop::Cop::Corrector',
	'RuboCop::Cop::IgnoredMethods',
	'RuboCop::Cop::IgnoredNode',
	'RuboCop::Cop::IgnoredPattern',
	'RuboCop::Cop::MethodPreference',
	'RuboCop::Cop::Offense',
	'RuboCop::Cop::RangeHelp',
	'RuboCop::Cop::Registry',
	'RuboCop::Cop::Util',
	'RuboCop::DirectiveComment',
	'RuboCop::Error',
	'RuboCop::ExcludeLimit',
	'RuboCop::Ext::Comment',
	'RuboCop::Ext::ProcessedSource',
	'RuboCop::Ext::Range',
	'RuboCop::FileFinder',
	'RuboCop::Formatter::TextUtil',
	'RuboCop::Formatter::PathUtil',
	'RuboCop::Options',
	'RuboCop::ResultCache',
	'RuboCop::RSpec::ExpectOffense',
	'RuboCop::Runner',
	'RuboCop::TargetFinder',
	'RuboCop::Version',
]

const typecheck_rbi_header = '# typed: true\n\n# This file is autogenerated. Do not edit it by hand.\n# To regenerate, run `brew typecheck --update rubocop`.'
const typecheck_failure_help = 'Check https://docs.brew.sh/Typechecking for more information on how to resolve these errors.\n'

pub struct TypecheckOptions {
pub:
	fix                    bool
	quiet                  bool
	update                 bool
	update_all             bool
	suggest_typed          bool
	lsp                    bool
	debug                  bool
	directory              string
	file                   string
	ignore                 string
	tap_directories        []string
	valid_gem_groups       []string
	library_path           string
	original_paths         []string
	watchman_path          string
	sorbet_static_gem_path string = 'sorbet-static'
	uid                    int = -1
	euid                   int = -1
	sorbet_success         bool = true
}

pub struct TypecheckCommand {
pub:
	arguments         []string
	working_directory string
	safe              bool
}

pub struct TypecheckEnvironmentPlan {
pub:
	library_directory string
	command_directory string
	uid               int
	euid              int
	change_privilege  bool
	privilege_target  int
	original_paths    []string
}

pub struct TypecheckRunPlan {
pub:
	mode             string
	bundler_groups   []string
	commands         []TypecheckCommand
	headings         []string
	environment      TypecheckEnvironmentPlan
	trim_rubocop_rbi bool
	failed           bool
	stderr           string
}

pub struct TypecheckTrimResult {
pub:
	path             string
	found            bool
	parsed           bool
	written          bool
	original_content string
	trimmed_content  string
	kept_names       []string
	removed_names    []string
}

pub enum TypecheckRbiNodeKind {
	class_or_module
	constant
	other
}

pub struct TypecheckRbiNode {
pub:
	kind       TypecheckRbiNodeKind
	full_name  string
	start_line int
	end_line   int
	keep       bool
}

fn typecheck_value_string(value brew_runtime.Value, name string) !string {
	if value.type_name != 'String' && value.type_name != 'Pathname' {
		return error('${name} must be a String or Pathname')
	}
	return value.as_string()
}

fn typecheck_take_option_value(argv []string, position int, option string) !(string, int) {
	if position + 1 >= argv.len {
		return error('${option} requires a value')
	}
	next_position := position + 1
	return argv[next_position], next_position
}

pub fn parse_typecheck_args(argv []string) !TypecheckOptions {
	mut fix := false
	mut quiet := false
	mut update := false
	mut update_all := false
	mut suggest_typed := false
	mut lsp := false
	mut debug := false
	mut directory := ''
	mut file := ''
	mut ignore := ''
	mut taps := []string{}
	mut position := 0
	for position < argv.len {
		argument := argv[position]
		match argument {
			'--fix' {
				fix = true
			}
			'-q', '--quiet' {
				quiet = true
			}
			'--update' {
				update = true
			}
			'--update-all' {
				update_all = true
			}
			'--suggest-typed' {
				suggest_typed = true
			}
			'--lsp' {
				lsp = true
			}
			'--debug' {
				debug = true
			}
			'--dir', '--file', '--ignore' {
				value, next_position := typecheck_take_option_value(argv, position, argument)!
				position = next_position
				if argument == '--dir' {
					directory = value
				} else if argument == '--file' {
					file = value
				} else {
					ignore = value
				}
			}
			else {
				if argument.starts_with('--dir=') {
					directory = argument.all_after('=')
				} else if argument.starts_with('--file=') {
					file = argument.all_after('=')
				} else if argument.starts_with('--ignore=') {
					ignore = argument.all_after('=')
				} else if argument.starts_with('-') {
					return error('unknown option: ${argument}')
				} else {
					taps << argument
				}
			}
		}
		position++
	}
	if directory != '' && file != '' {
		return error('Options --dir and --file are mutually exclusive.')
	}
	if lsp && (update || update_all || fix) {
		return error('Option --lsp conflicts with --update, --update-all, and --fix.')
	}
	if suggest_typed && !update {
		return error('Option --suggest-typed requires --update.')
	}
	return TypecheckOptions{
		fix: fix
		quiet: quiet
		update: update
		update_all: update_all
		suggest_typed: suggest_typed
		lsp: lsp
		debug: debug
		directory: directory
		file: file
		ignore: ignore
		tap_directories: taps
	}
}

fn validate_typecheck_options(options TypecheckOptions) ! {
	if options.directory != '' && options.file != '' {
		return error('Options --dir and --file are mutually exclusive.')
	}
	if (options.directory != '' || options.file != '') && options.tap_directories.len > 0 {
		return error('Cannot use `--dir` or `--file` when specifying a tap.')
	}
	if options.fix && options.tap_directories.len > 0 {
		return error('Cannot use `--fix` when specifying a tap.')
	}
	if options.lsp && (options.update || options.update_all || options.fix) {
		return error('Option --lsp conflicts with --update, --update-all, and --fix.')
	}
	if options.suggest_typed && !options.update {
		return error('Option --suggest-typed requires --update.')
	}
}

fn typecheck_command(arguments []string, working_directory string, safe bool) TypecheckCommand {
	return TypecheckCommand{
		arguments: arguments
		working_directory: working_directory
		safe: safe
	}
}

pub fn plan_typecheck(options TypecheckOptions) !TypecheckRunPlan {
	validate_typecheck_options(options)!
	update_mode := options.update || options.update_all
	library_path := if options.library_path == '' { '.' } else { options.library_path }
	uid := if options.uid >= 0 { options.uid } else { os.getuid() }
	euid := if options.euid >= 0 { options.euid } else { os.geteuid() }
	mut command_directory := library_path
	mut commands := []TypecheckCommand{}
	mut headings := []string{}
	groups := if update_mode { options.valid_gem_groups.clone() } else { ['typecheck'] }
	if update_mode {
		commands << typecheck_command(['bundle', 'exec', 'tapioca', 'annotations'], library_path, true)
		mut dsl := ['bundle', 'exec', 'tapioca', 'dsl']
		if options.debug {
			dsl << '--workers=1'
		}
		commands << typecheck_command(dsl, library_path, true)
		mut gem := ['bundle', 'exec', 'tapioca', 'gem']
		if options.update_all {
			gem << '--all'
		}
		headings << 'Updating Tapioca RBI files...'
		commands << typecheck_command(gem, library_path, true)
		headings << "Trimming RuboCop RBI because by default it's massive..."
		if options.suggest_typed {
			headings << 'Checking if we can bump Sorbet `typed` sigils...'
			sorbet_bin := os.join_path(options.sorbet_static_gem_path, 'libexec', 'sorbet')
			commands << typecheck_command(['bundle', 'exec', 'spoom', 'srb', 'bump', '--from', 'false',
				'--to', 'true', '--sorbet', sorbet_bin], library_path, false)
			commands << typecheck_command(['bundle', 'exec', 'spoom', 'srb', 'bump', '--from', 'true',
				'--to', 'strict', '--sorbet', sorbet_bin], library_path, false)
		}
		return TypecheckRunPlan{
			mode: 'update'
			bundler_groups: groups
			commands: commands
			headings: headings
			environment: TypecheckEnvironmentPlan{
				library_directory: library_path
				command_directory: library_path
				uid: uid
				euid: euid
				change_privilege: uid != euid
				privilege_target: euid
				original_paths: options.original_paths.clone()
			}
			trim_rubocop_rbi: true
		}
	}

	mut srb_exec := ['bundle', 'exec', 'srb', 'tc']
	if options.quiet {
		srb_exec << '--quiet'
	}
	if options.fix {
		srb_exec << '--suppress-error-code'
		srb_exec << '7003'
		srb_exec << '--autocorrect'
	}
	if options.lsp {
		srb_exec << '--lsp'
		if options.watchman_path != '' {
			srb_exec << '--watchman-path'
			srb_exec << options.watchman_path
		} else {
			srb_exec << '--disable-watchman'
		}
	}
	if options.ignore != '' {
		srb_exec << '--ignore'
		srb_exec << options.ignore
	}
	if options.file != '' || options.directory != '' || options.tap_directories.len > 0 {
		command_directory = os.join_path(library_path, 'sorbet')
		if options.file != '' {
			srb_exec << '--file'
			srb_exec << if os.is_abs_path(options.file) {
				options.file
			} else {
				'../${options.file}'
			}
		} else if options.directory != '' {
			srb_exec << '--dir'
			srb_exec << if os.is_abs_path(options.directory) {
				options.directory
			} else {
				'../${options.directory}'
			}
		}
		for tap_directory in options.tap_directories {
			srb_exec << '--dir'
			srb_exec << tap_directory
		}
	}
	commands << typecheck_command(srb_exec, command_directory, false)
	return TypecheckRunPlan{
		mode: if options.tap_directories.len > 0 { 'tap' } else { 'typecheck' }
		bundler_groups: groups
		commands: commands
		environment: TypecheckEnvironmentPlan{
			library_directory: library_path
			command_directory: command_directory
			uid: uid
			euid: euid
			change_privilege: uid != euid
			privilege_target: euid
			original_paths: options.original_paths.clone()
		}
		failed: !options.sorbet_success
		stderr: if options.sorbet_success { '' } else { typecheck_failure_help }
	}
}

pub fn extract_constant_path_parts(constant_path string) []string {
	path := constant_path.trim_space().trim_left(':')
	return path.split('::').map(it.trim_space()).filter(it != '')
}

pub fn extract_typecheck_full_name(declaration string) string {
	mut path := declaration.trim_space()
	if path.starts_with('class ') {
		path = path[6..].trim_space()
	} else if path.starts_with('module ') {
		path = path[7..].trim_space()
	} else {
		return ''
	}
	if path.starts_with('<<') {
		return ''
	}
	path = path.split('<')[0].split(';')[0].trim_space()
	return extract_constant_path_parts(path).join('::')
}

fn typecheck_lines(content string) []string {
	mut lines := []string{}
	mut start := 0
	for index, byte in content {
		if byte == `\n` {
			lines << content[start..index + 1]
			start = index + 1
		}
	}
	if start < content.len {
		lines << content[start..]
	}
	return lines
}

fn typecheck_code_before_comment(line string) string {
	mut single_quoted := false
	mut double_quoted := false
	mut escaped := false
	for index, byte in line {
		if escaped {
			escaped = false
			continue
		}
		if byte == `\\` && (single_quoted || double_quoted) {
			escaped = true
			continue
		}
		if byte == `'` && !double_quoted {
			single_quoted = !single_quoted
		} else if byte == `"` && !single_quoted {
			double_quoted = !double_quoted
		} else if byte == `#` && !single_quoted && !double_quoted {
			return line[..index]
		}
	}
	return line
}

fn typecheck_block_delta(line string) int {
	clean := typecheck_code_before_comment(line)
	mut delta := 0
	for raw_segment in clean.split(';') {
		segment := raw_segment.trim_space()
		if segment == '' {
			continue
		}
		if segment == 'end' || segment.starts_with('end ') {
			delta--
		}
		for opener in ['class ', 'module ', 'def ', 'if ', 'unless ', 'case ', 'while ', 'until ',
			'for '] {
			if segment.starts_with(opener) {
				delta++
				break
			}
		}
		if segment == 'begin' || segment.ends_with(' do') || segment.contains(' do |') {
			delta++
		}
	}
	return delta
}

fn typecheck_constant_name(line string) string {
	clean := typecheck_code_before_comment(line).trim_space()
	if !clean.contains('=') {
		return ''
	}
	lhs := clean.all_before('=').trim_space()
	if lhs.contains('::') || lhs == '' {
		return ''
	}
	if lhs[0] < `A` || lhs[0] > `Z` {
		return ''
	}
	for byte in lhs.bytes()[1..] {
		if !((byte >= `A` && byte <= `Z`) || (byte >= `a` && byte <= `z`)
			|| (byte >= `0` && byte <= `9`) || byte == `_`) {
			return ''
		}
	}
	return lhs
}

fn typecheck_essential_constant(name string) bool {
	return name.bytes().all((it >= `A` && it <= `Z`) || (it >= `0` && it <= `9`) || it == `_`)
}

pub fn parse_typecheck_rbi(content string) ![]TypecheckRbiNode {
	lines := typecheck_lines(content)
	mut nodes := []TypecheckRbiNode{}
	mut index := 0
	for index < lines.len {
		trimmed := lines[index].trim_space()
		if trimmed == '' || trimmed.starts_with('#') {
			index++
			continue
		}
		start := index
		if trimmed.starts_with('class ') || trimmed.starts_with('module ') {
			mut depth := 0
			for index < lines.len {
				depth += typecheck_block_delta(lines[index])
				if depth <= 0 {
					break
				}
				index++
			}
			if index >= lines.len || depth != 0 {
				return error('unterminated class or module at line ${start + 1}')
			}
			full_name := extract_typecheck_full_name(trimmed)
			keep := full_name == '' || typecheck_rubocop_allowlist.any(full_name.starts_with(it))
			nodes << TypecheckRbiNode{
				kind: .class_or_module
				full_name: full_name
				start_line: start
				end_line: index
				keep: keep
			}
		} else {
			constant_name := typecheck_constant_name(trimmed)
			if constant_name != '' {
				nodes << TypecheckRbiNode{
					kind: .constant
					full_name: constant_name
					start_line: start
					end_line: start
					keep: typecheck_essential_constant(constant_name)
				}
			} else {
				nodes << TypecheckRbiNode{
					kind: .other
					start_line: start
					end_line: start
					keep: true
				}
			}
		}
		index++
	}
	return nodes
}

pub fn generate_typecheck_trimmed_rbi(original_content string, nodes []TypecheckRbiNode) string {
	lines := typecheck_lines(original_content)
	mut output := []string{}
	if nodes.len > 0 {
		for index in 0 .. nodes[0].start_line {
			if index < lines.len {
				output << lines[index]
			}
		}
	}
	for node in nodes {
		if !node.keep {
			continue
		}
		for index in node.start_line .. node.end_line + 1 {
			if index < lines.len {
				output << lines[index]
			}
		}
		output << '\n'
	}
	if output.len == 0 {
		return typecheck_rbi_header
	}
	return output.join('')
}

pub fn trim_typecheck_rubocop_rbi(path_pattern string) !TypecheckTrimResult {
	mut files := os.glob(path_pattern) or { []string{} }
	if files.len == 0 && os.exists(path_pattern) {
		files << path_pattern
	}
	if files.len == 0 || !os.exists(files[0]) {
		return TypecheckTrimResult{}
	}
	path := files[0]
	original := os.read_file(path)!
	nodes := parse_typecheck_rbi(original) or {
		return TypecheckTrimResult{
			path: path
			found: true
			original_content: original
		}
	}
	trimmed := generate_typecheck_trimmed_rbi(original, nodes)
	os.write_file(path, trimmed)!
	return TypecheckTrimResult{
		path: path
		found: true
		parsed: true
		written: true
		original_content: original
		trimmed_content: trimmed
		kept_names: nodes.filter(it.keep && it.full_name != '').map(it.full_name)
		removed_names: nodes.filter(!it.keep && it.full_name != '').map(it.full_name)
	}
}

@[heap]
pub struct TypecheckInput {
pub:
	options TypecheckOptions
}

pub fn typecheck_input_boundary(input &TypecheckInput) brew_runtime.Value {
	return brew_runtime.structured_value('Homebrew::DevCmd::Typecheck::Input', '', {
		'typecheck_input_address': u64(voidptr(input)).str()
	})
}

fn typecheck_input_from_value(value brew_runtime.Value) &TypecheckInput {
	address := value.attributes['typecheck_input_address'] or { panic('invalid Typecheck input') }
	return unsafe { &TypecheckInput(voidptr(address.u64())) }
}

fn typecheck_commands_value(commands []TypecheckCommand) brew_runtime.Value {
	return brew_runtime.array_value(commands.map(brew_runtime.map_value({
		'arguments':         brew_runtime.string_array_value(it.arguments)
		'working_directory': brew_runtime.string_value(it.working_directory)
		'safe':              brew_runtime.bool_value(it.safe)
	})))
}

fn typecheck_plan_value(plan TypecheckRunPlan) brew_runtime.Value {
	return brew_runtime.map_value({
		'mode':              brew_runtime.string_value(plan.mode)
		'bundler_groups':    brew_runtime.string_array_value(plan.bundler_groups)
		'commands':          typecheck_commands_value(plan.commands)
		'headings':          brew_runtime.string_array_value(plan.headings)
		'trim_rubocop_rbi':  brew_runtime.bool_value(plan.trim_rubocop_rbi)
		'change_privilege':  brew_runtime.bool_value(plan.environment.change_privilege)
		'privilege_target':  brew_runtime.int_value(plan.environment.privilege_target)
		'command_directory': brew_runtime.string_value(plan.environment.command_directory)
		'failed':            brew_runtime.bool_value(plan.failed)
		'stderr':            brew_runtime.string_value(plan.stderr)
	})
}

fn typecheck_trim_result_value(result TypecheckTrimResult) brew_runtime.Value {
	return brew_runtime.map_value({
		'path':            brew_runtime.string_value(result.path)
		'found':           brew_runtime.bool_value(result.found)
		'parsed':          brew_runtime.bool_value(result.parsed)
		'written':         brew_runtime.bool_value(result.written)
		'trimmed_content': brew_runtime.string_value(result.trimmed_content)
		'kept_names':      brew_runtime.string_array_value(result.kept_names)
		'removed_names':   brew_runtime.string_array_value(result.removed_names)
	})
}

// Ruby method `run` at line 46.
pub fn ruby_typecheck_l46_d1_run(args ...brew_runtime.Value) brew_runtime.Value {
	if args.len == 0 {
		return brew_runtime.object_value('ArgumentError', 'command input is required')
	}
	plan := plan_typecheck(typecheck_input_from_value(args[0]).options) or {
		return brew_runtime.object_value('UsageError', err.msg())
	}
	return typecheck_plan_value(plan)
}

// Ruby method `trim_rubocop_rbi(path: HOMEBREW_LIBRARY_PATH/"sorbet/rbi/gems/rubocop@*.rbi")` at line 144.
pub fn ruby_typecheck_l144_d2_trim_rubocop_rbi(args ...brew_runtime.Value) brew_runtime.Value {
	if args.len == 0 {
		return brew_runtime.object_value('ArgumentError', 'path is required')
	}
	path := typecheck_value_string(args[0], 'path') or {
		return brew_runtime.object_value('TypeError', err.msg())
	}
	result := trim_typecheck_rubocop_rbi(path) or {
		return brew_runtime.object_value('SystemCallError', err.msg())
	}
	return typecheck_trim_result_value(result)
}

// Ruby method `extract_full_name(node)` at line 218.
pub fn ruby_typecheck_l218_d3_extract_full_name(args ...brew_runtime.Value) brew_runtime.Value {
	if args.len == 0 {
		return brew_runtime.object_value('ArgumentError', 'node is required')
	}
	return brew_runtime.string_value(extract_typecheck_full_name(args[0].as_string()))
}

// Ruby method `extract_constant_path_parts(constant_path)` at line 237.
pub fn ruby_typecheck_l237_d4_extract_constant_path_parts(args ...brew_runtime.Value) brew_runtime.Value {
	if args.len == 0 {
		return brew_runtime.object_value('ArgumentError', 'constant_path is required')
	}
	return brew_runtime.string_array_value(extract_constant_path_parts(args[0].as_string()))
}

// Ruby method `generate_trimmed_rbi(original_content, nodes_to_keep, parsed)` at line 264.
pub fn ruby_typecheck_l264_d5_generate_trimmed_rbi(args ...brew_runtime.Value) brew_runtime.Value {
	if args.len == 0 {
		return brew_runtime.object_value('ArgumentError', 'original_content is required')
	}
	nodes := parse_typecheck_rbi(args[0].as_string()) or {
		return brew_runtime.object_value('Prism::ParseError', err.msg())
	}
	return brew_runtime.string_value(generate_typecheck_trimmed_rbi(args[0].as_string(), nodes))
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "abstract_command"
// 5: require "fileutils"
// 6:
// 7: module Homebrew
// 8:   module DevCmd
// 9:     class Typecheck < AbstractCommand
// 10:       include FileUtils
// 11:
// 12:       cmd_args do
// 13:         description <<~EOS
// 14:           Check for typechecking errors using Sorbet.
// 15:         EOS
// 16:         switch "--fix",
// 17:                description: "Automatically fix type errors."
// 18:         switch "-q", "--quiet",
// 19:                description: "Silence all non-critical errors."
// 20:         switch "--update",
// 21:                description: "Update RBI files."
// 22:         switch "--update-all",
// 23:                description: "Update all RBI files rather than just updated gems."
// 24:         switch "--suggest-typed",
// 25:                depends_on:  "--update",
// 26:                description: "Try upgrading `typed` sigils."
// 27:         switch "--lsp",
// 28:                description: "Start the Sorbet LSP server."
// 29:         flag   "--dir=",
// 30:                description: "Typecheck all files in a specific directory."
// 31:         flag   "--file=",
// 32:                description: "Typecheck a single file."
// 33:         flag   "--ignore=",
// 34:                description: "Ignores input files that contain the given string " \
// 35:                             "in their paths (relative to the input path passed to Sorbet)."
// 36:
// 37:         conflicts "--dir", "--file"
// 38:         conflicts "--lsp", "--update"
// 39:         conflicts "--lsp", "--update-all"
// 40:         conflicts "--lsp", "--fix"
// 41:
// 42:         named_args :tap
// 43:       end
// 44:
// 45:       sig { override.void }
// 46:       def run
// 47:         if (args.dir.present? || args.file.present?) && args.named.present?
// 48:           raise UsageError, "Cannot use `--dir` or `--file` when specifying a tap."
// 49:         elsif args.fix? && args.named.present?
// 50:           raise UsageError, "Cannot use `--fix` when specifying a tap."
// 51:         end
// 52:
// 53:         update = args.update? || args.update_all?
// 54:         groups = update ? Homebrew.valid_gem_groups : ["typecheck"]
// 55:         Homebrew.install_bundler_gems!(groups:)
// 56:
// 57:         # Sorbet doesn't use bash privileged mode so we align EUID and UID here.
// 58:         Process::UID.change_privilege(Process.euid) if Process.euid != Process.uid
// 59:
// 60:         HOMEBREW_LIBRARY_PATH.cd do
// 61:           if update
// 62:             workers = args.debug? ? ["--workers=1"] : []
// 63:             safe_system "bundle", "exec", "tapioca", "annotations"
// 64:             safe_system "bundle", "exec", "tapioca", "dsl", *workers
// 65:             # Prefer adding args here: Library/Homebrew/sorbet/tapioca/config.yml
// 66:             tapioca_args = args.update_all? ? ["--all"] : []
// 67:
// 68:             ohai "Updating Tapioca RBI files..."
// 69:             safe_system "bundle", "exec", "tapioca", "gem", *tapioca_args
// 70:
// 71:             ohai "Trimming RuboCop RBI because by default it's massive..."
// 72:             trim_rubocop_rbi
// 73:
// 74:             if args.suggest_typed?
// 75:               ohai "Checking if we can bump Sorbet `typed` sigils..."
// 76:               # --sorbet needed because of https://github.com/Shopify/spoom/issues/488
// 77:               #
// 78:               # Use the native sorbet binary directly to avoid Ruby version conflicts.
// 79:               # spoom's exec uses Bundler.with_unbundled_env which can cause `#!/usr/bin/env ruby`
// 80:               # scripts to use the wrong Ruby version (e.g., system Ruby 2.6 on macOS).
// 81:               sorbet_path = Gem::Specification.find_by_name("sorbet-static").full_gem_path
// 82:               sorbet_bin = File.join(sorbet_path, "libexec", "sorbet")
// 83:               system "bundle", "exec", "spoom", "srb", "bump", "--from", "false", "--to", "true",
// 84:                      "--sorbet", sorbet_bin
// 85:               system "bundle", "exec", "spoom", "srb", "bump", "--from", "true", "--to", "strict",
// 86:                      "--sorbet", sorbet_bin
// 87:             end
// 88:
// 89:             return
// 90:           end
// 91:
// 92:           srb_exec = %w[bundle exec srb tc]
// 93:
// 94:           srb_exec << "--quiet" if args.quiet?
// 95:
// 96:           if args.fix?
// 97:             # Auto-correcting method names is almost always wrong.
// 98:             srb_exec << "--suppress-error-code" << "7003"
// 99:
// 100:             srb_exec << "--autocorrect"
// 101:           end
// 102:
// 103:           if args.lsp?
// 104:             srb_exec << "--lsp"
// 105:             if (watchman = which("watchman", ORIGINAL_PATHS))
// 106:               srb_exec << "--watchman-path" << watchman.to_s
// 107:             else
// 108:               srb_exec << "--disable-watchman"
// 109:             end
// 110:           end
// 111:
// 112:           srb_exec += ["--ignore", args.ignore] if args.ignore.present?
// 113:           if args.file.present? || args.dir.present? || (tap_dirs = args.named.to_paths(only: :tap)).present?
// 114:             cd("sorbet") do
// 115:               path = if (file = args.file.presence)
// 116:                 srb_exec << "--file"
// 117:                 Pathname(file)
// 118:               elsif (dir = args.dir.presence)
// 119:                 srb_exec << "--dir"
// 120:                 Pathname(dir)
// 121:               end
// 122:               if path
// 123:                 srb_exec << if path.absolute?
// 124:                   path.to_path
// 125:                 else
// 126:                   "../#{path}"
// 127:                 end
// 128:               end
// 129:               tap_dirs&.each do |tap_dir|
// 130:                 srb_exec += ["--dir", tap_dir.to_s]
// 131:               end
// 132:             end
// 133:           end
// 134:           success = system(*srb_exec)
// 135:           return if success
// 136:
// 137:           $stderr.puts "Check #{Formatter.url("https://docs.brew.sh/Typechecking")} for " \
// 138:                        "more information on how to resolve these errors."
// 139:           Homebrew.failed = true
// 140:         end
// 141:       end
// 142:
// 143:       sig { params(path: T.any(String, Pathname)).void }
// 144:       def trim_rubocop_rbi(path: HOMEBREW_LIBRARY_PATH/"sorbet/rbi/gems/rubocop@*.rbi")
// 145:         rbi_file = Dir.glob(path).first
// 146:         return unless rbi_file.present?
// 147:         return unless (rbi_path = Pathname.new(rbi_file)).exist?
// 148:
// 149:         require "prism"
// 150:         original_content = rbi_path.read
// 151:         parsed = Prism.parse(original_content)
// 152:         return unless parsed.success?
// 153:
// 154:         allowlist = %w[
// 155:           CopHelper
// 156:           Parser::Source
// 157:           RuboCop::AST::Node
// 158:           RuboCop::AST::NodePattern
// 159:           RuboCop::AST::ProcessedSource
// 160:           RuboCop::CLI
// 161:           RuboCop::Config
// 162:           RuboCop::Cop::AllowedPattern
// 163:           RuboCop::Cop::AllowedMethods
// 164:           RuboCop::Cop::AutoCorrector
// 165:           RuboCop::Cop::AutocorrectLogic
// 166:           RuboCop::Cop::Base
// 167:           RuboCop::Cop::CommentsHelp
// 168:           RuboCop::Cop::ConfigurableFormatting
// 169:           RuboCop::Cop::ConfigurableNaming
// 170:           RuboCop::Cop::Corrector
// 171:           RuboCop::Cop::IgnoredMethods
// 172:           RuboCop::Cop::IgnoredNode
// 173:           RuboCop::Cop::IgnoredPattern
// 174:           RuboCop::Cop::MethodPreference
// 175:           RuboCop::Cop::Offense
// 176:           RuboCop::Cop::RangeHelp
// 177:           RuboCop::Cop::Registry
// 178:           RuboCop::Cop::Util
// 179:           RuboCop::DirectiveComment
// 180:           RuboCop::Error
// 181:           RuboCop::ExcludeLimit
// 182:           RuboCop::Ext::Comment
// 183:           RuboCop::Ext::ProcessedSource
// 184:           RuboCop::Ext::Range
// 185:           RuboCop::FileFinder
// 186:           RuboCop::Formatter::TextUtil
// 187:           RuboCop::Formatter::PathUtil
// 188:           RuboCop::Options
// 189:           RuboCop::ResultCache
// 190:           RuboCop::RSpec::ExpectOffense
// 191:           RuboCop::Runner
// 192:           RuboCop::TargetFinder
// 193:           RuboCop::Version
// 194:         ].freeze
// 195:
// 196:         nodes_to_keep = Set.new
// 197:
// 198:         parsed.value.statements.body.each do |node|
// 199:           case node
// 200:           when Prism::ModuleNode, Prism::ClassNode
// 201:             # Keep if it's in our allowlist or is a top-level essential node.
// 202:             full_name = extract_full_name(node)
// 203:             nodes_to_keep << node if full_name.blank? || allowlist.any? { |name| full_name.start_with?(name) }
// 204:           when Prism::ConstantWriteNode # Keep essential constants.
// 205:             nodes_to_keep << node if node.name.to_s.match?(/^[[:digit:][:upper:]_]+$/)
// 206:           else # Keep other top-level nodes (comments, etc.)
// 207:             nodes_to_keep << node
// 208:           end
// 209:         end
// 210:
// 211:         new_content = generate_trimmed_rbi(original_content, nodes_to_keep, parsed)
// 212:         rbi_path.write(new_content)
// 213:       end
// 214:
// 215:       private
// 216:
// 217:       sig { params(node: Prism::Node).returns(String) }
// 218:       def extract_full_name(node)
// 219:         case node
// 220:         when Prism::ModuleNode, Prism::ClassNode
// 221:           parts = []
// 222:
// 223:           constant_path = node.constant_path
// 224:           if constant_path.is_a?(Prism::ConstantReadNode)
// 225:             parts << constant_path.name.to_s
// 226:           elsif constant_path.is_a?(Prism::ConstantPathNode)
// 227:             parts.concat(extract_constant_path_parts(constant_path))
// 228:           end
// 229:
// 230:           parts.join("::")
// 231:         else
// 232:           ""
// 233:         end
// 234:       end
// 235:
// 236:       sig { params(constant_path: T.any(Prism::ConstantPathNode, Prism::Node)).returns(T::Array[String]) }
// 237:       def extract_constant_path_parts(constant_path)
// 238:         parts = []
// 239:         current = T.let(constant_path, T.nilable(Prism::Node))
// 240:
// 241:         while current
// 242:           case current
// 243:           when Prism::ConstantPathNode
// 244:             parts.unshift(current.name.to_s)
// 245:             current = current.parent
// 246:           when Prism::ConstantReadNode
// 247:             parts.unshift(current.name.to_s)
// 248:             break
// 249:           else
// 250:             break
// 251:           end
// 252:         end
// 253:
// 254:         parts
// 255:       end
// 256:
// 257:       sig {
// 258:         params(
// 259:           original_content: String,
// 260:           nodes_to_keep:    T::Set[Prism::Node],
// 261:           parsed:           Prism::ParseResult,
// 262:         ).returns(String)
// 263:       }
// 264:       def generate_trimmed_rbi(original_content, nodes_to_keep, parsed)
// 265:         lines = original_content.lines
// 266:         output_lines = []
// 267:
// 268:         first_node = parsed.value.statements.body.first
// 269:         if first_node
// 270:           first_line = first_node.location.start_line - 1
// 271:           (0...first_line).each { |i| output_lines << lines[i] if lines[i] }
// 272:         end
// 273:
// 274:         parsed.value.statements.body.each do |node|
// 275:           next unless nodes_to_keep.include?(node)
// 276:
// 277:           start_line = node.location.start_line - 1
// 278:           end_line = node.location.end_line - 1
// 279:
// 280:           (start_line..end_line).each { |i| output_lines << lines[i] if lines[i] }
// 281:           output_lines << "\n"
// 282:         end
// 283:
// 284:         header = <<~EOS.chomp
// 285:           # typed: true
// 286:
// 287:           # This file is autogenerated. Do not edit it by hand.
// 288:           # To regenerate, run `brew typecheck --update rubocop`.
// 289:         EOS
// 290:
// 291:         return header if output_lines.empty?
// 292:
// 293:         output_lines.join
// 294:       end
// 295:     end
// 296:   end
// 297: end
