module dev_cmd

import ruby
import os

// Translated from Homebrew/brew `dev-cmd/typecheck.rb`.

const typecheck_rubocop_allowlist = [
	'CopHelper',
	'Parser::Source',
	'RuboCop::AST::Node',
	'RuboCop::AST::NodePattern',
	'RuboCop::AST::ProcessedSource',
	'RuboCop::CLI',
	'RuboCop::Config',
	'RuboCop::Cop::AllowedPattern',
	'RuboCop::Cop::AllowedMethods',
	'RuboCop::Cop::AutoCorrector',
	'RuboCop::Cop::AutocorrectLogic',
	'RuboCop::Cop::Base',
	'RuboCop::Cop::CommentsHelp',
	'RuboCop::Cop::ConfigurableFormatting',
	'RuboCop::Cop::ConfigurableNaming',
	'RuboCop::Cop::Corrector',
	'RuboCop::Cop::IgnoredMethods',
	'RuboCop::Cop::IgnoredNode',
	'RuboCop::Cop::IgnoredPattern',
	'RuboCop::Cop::MethodPreference',
	'RuboCop::Cop::Offense',
	'RuboCop::Cop::RangeHelp',
	'RuboCop::Cop::Registry',
	'RuboCop::Cop::Util',
	'RuboCop::DirectiveComment',
	'RuboCop::Error',
	'RuboCop::ExcludeLimit',
	'RuboCop::Ext::Comment',
	'RuboCop::Ext::ProcessedSource',
	'RuboCop::Ext::Range',
	'RuboCop::FileFinder',
	'RuboCop::Formatter::TextUtil',
	'RuboCop::Formatter::PathUtil',
	'RuboCop::Options',
	'RuboCop::ResultCache',
	'RuboCop::RSpec::ExpectOffense',
	'RuboCop::Runner',
	'RuboCop::TargetFinder',
	'RuboCop::Version',
]

const typecheck_rbi_header = '# typed: true\n\n# This file is autogenerated. Do not edit it by hand.\n# To regenerate, run `brew typecheck --update rubocop`.'
const typecheck_failure_help = 'Check https://docs.brew.sh/Typechecking for more information on how to resolve these errors.\n'

pub struct TypecheckOptions {
pub:
	fix                    bool
	quiet                  bool
	update                 bool
	update_all             bool
	suggest_typed          bool
	lsp                    bool
	debug                  bool
	directory              string
	file                   string
	ignore                 string
	tap_directories        []string
	valid_gem_groups       []string
	library_path           string
	original_paths         []string
	watchman_path          string
	sorbet_static_gem_path string = 'sorbet-static'
	uid                    int = -1
	euid                   int = -1
	sorbet_success         bool = true
}

pub struct TypecheckCommand {
pub:
	arguments         []string
	working_directory string
	safe              bool
}

pub struct TypecheckEnvironmentPlan {
pub:
	library_directory string
	command_directory string
	uid               int
	euid              int
	change_privilege  bool
	privilege_target  int
	original_paths    []string
}

pub struct TypecheckRunPlan {
pub:
	mode             string
	bundler_groups   []string
	commands         []TypecheckCommand
	headings         []string
	environment      TypecheckEnvironmentPlan
	trim_rubocop_rbi bool
	failed           bool
	stderr           string
}

pub struct TypecheckTrimResult {
pub:
	path             string
	found            bool
	parsed           bool
	written          bool
	original_content string
	trimmed_content  string
	kept_names       []string
	removed_names    []string
}

pub enum TypecheckRbiNodeKind {
	class_or_module
	constant
	other
}

pub struct TypecheckRbiNode {
pub:
	kind       TypecheckRbiNodeKind
	full_name  string
	start_line int
	end_line   int
	keep       bool
}

fn typecheck_value_string(value ruby.Value, name string) !string {
	if value.type_name != 'String' && value.type_name != 'Pathname' {
		return error('${name} must be a String or Pathname')
	}
	return value.as_string()
}

fn typecheck_take_option_value(argv []string, position int, option string) !(string, int) {
	if position + 1 >= argv.len {
		return error('${option} requires a value')
	}
	next_position := position + 1
	return argv[next_position], next_position
}

pub fn parse_typecheck_args(argv []string) !TypecheckOptions {
	mut fix := false
	mut quiet := false
	mut update := false
	mut update_all := false
	mut suggest_typed := false
	mut lsp := false
	mut debug := false
	mut directory := ''
	mut file := ''
	mut ignore := ''
	mut taps := []string{}
	mut position := 0
	for position < argv.len {
		argument := argv[position]
		match argument {
			'--fix' {
				fix = true
			}
			'-q', '--quiet' {
				quiet = true
			}
			'--update' {
				update = true
			}
			'--update-all' {
				update_all = true
			}
			'--suggest-typed' {
				suggest_typed = true
			}
			'--lsp' {
				lsp = true
			}
			'--debug' {
				debug = true
			}
			'--dir', '--file', '--ignore' {
				value, next_position := typecheck_take_option_value(argv, position, argument)!
				position = next_position
				if argument == '--dir' {
					directory = value
				} else if argument == '--file' {
					file = value
				} else {
					ignore = value
				}
			}
			else {
				if argument.starts_with('--dir=') {
					directory = argument.all_after('=')
				} else if argument.starts_with('--file=') {
					file = argument.all_after('=')
				} else if argument.starts_with('--ignore=') {
					ignore = argument.all_after('=')
				} else if argument.starts_with('-') {
					return error('unknown option: ${argument}')
				} else {
					taps << argument
				}
			}
		}
		position++
	}
	if directory != '' && file != '' {
		return error('Options --dir and --file are mutually exclusive.')
	}
	if lsp && (update || update_all || fix) {
		return error('Option --lsp conflicts with --update, --update-all, and --fix.')
	}
	if suggest_typed && !update {
		return error('Option --suggest-typed requires --update.')
	}
	return TypecheckOptions{
		fix: fix
		quiet: quiet
		update: update
		update_all: update_all
		suggest_typed: suggest_typed
		lsp: lsp
		debug: debug
		directory: directory
		file: file
		ignore: ignore
		tap_directories: taps
	}
}

fn validate_typecheck_options(options TypecheckOptions) ! {
	if options.directory != '' && options.file != '' {
		return error('Options --dir and --file are mutually exclusive.')
	}
	if (options.directory != '' || options.file != '') && options.tap_directories.len > 0 {
		return error('Cannot use `--dir` or `--file` when specifying a tap.')
	}
	if options.fix && options.tap_directories.len > 0 {
		return error('Cannot use `--fix` when specifying a tap.')
	}
	if options.lsp && (options.update || options.update_all || options.fix) {
		return error('Option --lsp conflicts with --update, --update-all, and --fix.')
	}
	if options.suggest_typed && !options.update {
		return error('Option --suggest-typed requires --update.')
	}
}

fn typecheck_command(arguments []string, working_directory string, safe bool) TypecheckCommand {
	return TypecheckCommand{
		arguments: arguments
		working_directory: working_directory
		safe: safe
	}
}

pub fn plan_typecheck(options TypecheckOptions) !TypecheckRunPlan {
	validate_typecheck_options(options)!
	update_mode := options.update || options.update_all
	library_path := if options.library_path == '' { '.' } else { options.library_path }
	uid := if options.uid >= 0 { options.uid } else { os.getuid() }
	euid := if options.euid >= 0 { options.euid } else { os.geteuid() }
	mut command_directory := library_path
	mut commands := []TypecheckCommand{}
	mut headings := []string{}
	groups := if update_mode { options.valid_gem_groups.clone() } else { ['typecheck'] }
	if update_mode {
		commands << typecheck_command(['bundle', 'exec', 'tapioca', 'annotations'], library_path, true)
		mut dsl := ['bundle', 'exec', 'tapioca', 'dsl']
		if options.debug {
			dsl << '--workers=1'
		}
		commands << typecheck_command(dsl, library_path, true)
		mut gem := ['bundle', 'exec', 'tapioca', 'gem']
		if options.update_all {
			gem << '--all'
		}
		headings << 'Updating Tapioca RBI files...'
		commands << typecheck_command(gem, library_path, true)
		headings << "Trimming RuboCop RBI because by default it's massive..."
		if options.suggest_typed {
			headings << 'Checking if we can bump Sorbet `typed` sigils...'
			sorbet_bin := os.join_path(options.sorbet_static_gem_path, 'libexec', 'sorbet')
			commands << typecheck_command(['bundle', 'exec', 'spoom', 'srb', 'bump', '--from', 'false',
				'--to', 'true', '--sorbet', sorbet_bin], library_path, false)
			commands << typecheck_command(['bundle', 'exec', 'spoom', 'srb', 'bump', '--from', 'true',
				'--to', 'strict', '--sorbet', sorbet_bin], library_path, false)
		}
		return TypecheckRunPlan{
			mode: 'update'
			bundler_groups: groups
			commands: commands
			headings: headings
			environment: TypecheckEnvironmentPlan{
				library_directory: library_path
				command_directory: library_path
				uid: uid
				euid: euid
				change_privilege: uid != euid
				privilege_target: euid
				original_paths: options.original_paths.clone()
			}
			trim_rubocop_rbi: true
		}
	}

	mut srb_exec := ['bundle', 'exec', 'srb', 'tc']
	if options.quiet {
		srb_exec << '--quiet'
	}
	if options.fix {
		srb_exec << '--suppress-error-code'
		srb_exec << '7003'
		srb_exec << '--autocorrect'
	}
	if options.lsp {
		srb_exec << '--lsp'
		if options.watchman_path != '' {
			srb_exec << '--watchman-path'
			srb_exec << options.watchman_path
		} else {
			srb_exec << '--disable-watchman'
		}
	}
	if options.ignore != '' {
		srb_exec << '--ignore'
		srb_exec << options.ignore
	}
	if options.file != '' || options.directory != '' || options.tap_directories.len > 0 {
		command_directory = os.join_path(library_path, 'sorbet')
		if options.file != '' {
			srb_exec << '--file'
			srb_exec << if os.is_abs_path(options.file) {
				options.file
			} else {
				'../${options.file}'
			}
		} else if options.directory != '' {
			srb_exec << '--dir'
			srb_exec << if os.is_abs_path(options.directory) {
				options.directory
			} else {
				'../${options.directory}'
			}
		}
		for tap_directory in options.tap_directories {
			srb_exec << '--dir'
			srb_exec << tap_directory
		}
	}
	commands << typecheck_command(srb_exec, command_directory, false)
	return TypecheckRunPlan{
		mode: if options.tap_directories.len > 0 { 'tap' } else { 'typecheck' }
		bundler_groups: groups
		commands: commands
		environment: TypecheckEnvironmentPlan{
			library_directory: library_path
			command_directory: command_directory
			uid: uid
			euid: euid
			change_privilege: uid != euid
			privilege_target: euid
			original_paths: options.original_paths.clone()
		}
		failed: !options.sorbet_success
		stderr: if options.sorbet_success { '' } else { typecheck_failure_help }
	}
}

pub fn extract_constant_path_parts(constant_path string) []string {
	path := constant_path.trim_space().trim_left(':')
	return path.split('::').map(it.trim_space()).filter(it != '')
}

pub fn extract_typecheck_full_name(declaration string) string {
	mut path := declaration.trim_space()
	if path.starts_with('class ') {
		path = path[6..].trim_space()
	} else if path.starts_with('module ') {
		path = path[7..].trim_space()
	} else {
		return ''
	}
	if path.starts_with('<<') {
		return ''
	}
	path = path.split('<')[0].split(';')[0].trim_space()
	return extract_constant_path_parts(path).join('::')
}

fn typecheck_lines(content string) []string {
	mut lines := []string{}
	mut start := 0
	for index, byte in content {
		if byte == `\n` {
			lines << content[start..index + 1]
			start = index + 1
		}
	}
	if start < content.len {
		lines << content[start..]
	}
	return lines
}

fn typecheck_code_before_comment(line string) string {
	mut single_quoted := false
	mut double_quoted := false
	mut escaped := false
	for index, byte in line {
		if escaped {
			escaped = false
			continue
		}
		if byte == `\\` && (single_quoted || double_quoted) {
			escaped = true
			continue
		}
		if byte == `'` && !double_quoted {
			single_quoted = !single_quoted
		} else if byte == `"` && !single_quoted {
			double_quoted = !double_quoted
		} else if byte == `#` && !single_quoted && !double_quoted {
			return line[..index]
		}
	}
	return line
}

fn typecheck_block_delta(line string) int {
	clean := typecheck_code_before_comment(line)
	mut delta := 0
	for raw_segment in clean.split(';') {
		segment := raw_segment.trim_space()
		if segment == '' {
			continue
		}
		if segment == 'end' || segment.starts_with('end ') {
			delta--
		}
		for opener in ['class ', 'module ', 'def ', 'if ', 'unless ', 'case ', 'while ', 'until ',
			'for '] {
			if segment.starts_with(opener) {
				delta++
				break
			}
		}
		if segment == 'begin' || segment.ends_with(' do') || segment.contains(' do |') {
			delta++
		}
	}
	return delta
}

fn typecheck_constant_name(line string) string {
	clean := typecheck_code_before_comment(line).trim_space()
	if !clean.contains('=') {
		return ''
	}
	lhs := clean.all_before('=').trim_space()
	if lhs.contains('::') || lhs == '' {
		return ''
	}
	if lhs[0] < `A` || lhs[0] > `Z` {
		return ''
	}
	for byte in lhs.bytes()[1..] {
		if !((byte >= `A` && byte <= `Z`) || (byte >= `a` && byte <= `z`)
			|| (byte >= `0` && byte <= `9`) || byte == `_`) {
			return ''
		}
	}
	return lhs
}

fn typecheck_essential_constant(name string) bool {
	return name.bytes().all((it >= `A` && it <= `Z`) || (it >= `0` && it <= `9`) || it == `_`)
}

pub fn parse_typecheck_rbi(content string) ![]TypecheckRbiNode {
	lines := typecheck_lines(content)
	mut nodes := []TypecheckRbiNode{}
	mut index := 0
	for index < lines.len {
		trimmed := lines[index].trim_space()
		if trimmed == '' || trimmed.starts_with('#') {
			index++
			continue
		}
		start := index
		if trimmed.starts_with('class ') || trimmed.starts_with('module ') {
			mut depth := 0
			for index < lines.len {
				depth += typecheck_block_delta(lines[index])
				if depth <= 0 {
					break
				}
				index++
			}
			if index >= lines.len || depth != 0 {
				return error('unterminated class or module at line ${start + 1}')
			}
			full_name := extract_typecheck_full_name(trimmed)
			keep := full_name == '' || typecheck_rubocop_allowlist.any(full_name.starts_with(it))
			nodes << TypecheckRbiNode{
				kind: .class_or_module
				full_name: full_name
				start_line: start
				end_line: index
				keep: keep
			}
		} else {
			constant_name := typecheck_constant_name(trimmed)
			if constant_name != '' {
				nodes << TypecheckRbiNode{
					kind: .constant
					full_name: constant_name
					start_line: start
					end_line: start
					keep: typecheck_essential_constant(constant_name)
				}
			} else {
				nodes << TypecheckRbiNode{
					kind: .other
					start_line: start
					end_line: start
					keep: true
				}
			}
		}
		index++
	}
	return nodes
}

pub fn generate_typecheck_trimmed_rbi(original_content string, nodes []TypecheckRbiNode) string {
	lines := typecheck_lines(original_content)
	mut output := []string{}
	if nodes.len > 0 {
		for index in 0 .. nodes[0].start_line {
			if index < lines.len {
				output << lines[index]
			}
		}
	}
	for node in nodes {
		if !node.keep {
			continue
		}
		for index in node.start_line .. node.end_line + 1 {
			if index < lines.len {
				output << lines[index]
			}
		}
		output << '\n'
	}
	if output.len == 0 {
		return typecheck_rbi_header
	}
	return output.join('')
}

pub fn trim_typecheck_rubocop_rbi(path_pattern string) !TypecheckTrimResult {
	mut files := os.glob(path_pattern) or { []string{} }
	if files.len == 0 && os.exists(path_pattern) {
		files << path_pattern
	}
	if files.len == 0 || !os.exists(files[0]) {
		return TypecheckTrimResult{}
	}
	path := files[0]
	original := os.read_file(path)!
	nodes := parse_typecheck_rbi(original) or {
		return TypecheckTrimResult{
			path: path
			found: true
			original_content: original
		}
	}
	trimmed := generate_typecheck_trimmed_rbi(original, nodes)
	os.write_file(path, trimmed)!
	return TypecheckTrimResult{
		path: path
		found: true
		parsed: true
		written: true
		original_content: original
		trimmed_content: trimmed
		kept_names: nodes.filter(it.keep && it.full_name != '').map(it.full_name)
		removed_names: nodes.filter(!it.keep && it.full_name != '').map(it.full_name)
	}
}

@[heap]
pub struct TypecheckInput {
pub:
	options TypecheckOptions
}

pub fn typecheck_input_boundary(input &TypecheckInput) ruby.Value {
	return ruby.structured_value('Homebrew::DevCmd::Typecheck::Input', '', {
		'typecheck_input_address': u64(voidptr(input)).str()
	})
}

fn typecheck_input_from_value(value ruby.Value) &TypecheckInput {
	address := value.attributes['typecheck_input_address'] or { panic('invalid Typecheck input') }
	return unsafe { &TypecheckInput(voidptr(address.u64())) }
}

fn typecheck_commands_value(commands []TypecheckCommand) ruby.Value {
	return ruby.array_value(commands.map(ruby.map_value({
		'arguments':         ruby.string_array_value(it.arguments)
		'working_directory': ruby.string_value(it.working_directory)
		'safe':              ruby.bool_value(it.safe)
	})))
}

fn typecheck_plan_value(plan TypecheckRunPlan) ruby.Value {
	return ruby.map_value({
		'mode':              ruby.string_value(plan.mode)
		'bundler_groups':    ruby.string_array_value(plan.bundler_groups)
		'commands':          typecheck_commands_value(plan.commands)
		'headings':          ruby.string_array_value(plan.headings)
		'trim_rubocop_rbi':  ruby.bool_value(plan.trim_rubocop_rbi)
		'change_privilege':  ruby.bool_value(plan.environment.change_privilege)
		'privilege_target':  ruby.int_value(plan.environment.privilege_target)
		'command_directory': ruby.string_value(plan.environment.command_directory)
		'failed':            ruby.bool_value(plan.failed)
		'stderr':            ruby.string_value(plan.stderr)
	})
}

fn typecheck_trim_result_value(result TypecheckTrimResult) ruby.Value {
	return ruby.map_value({
		'path':            ruby.string_value(result.path)
		'found':           ruby.bool_value(result.found)
		'parsed':          ruby.bool_value(result.parsed)
		'written':         ruby.bool_value(result.written)
		'trimmed_content': ruby.string_value(result.trimmed_content)
		'kept_names':      ruby.string_array_value(result.kept_names)
		'removed_names':   ruby.string_array_value(result.removed_names)
	})
}
