module linux

import ruby
import os

// Translated from Homebrew/brew `extend/os/linux/install.rb`.

pub const install_gcc_runtime_libs = [
	'libatomic.so.1',
	'libgcc_s.so.1',
	'libgomp.so.1',
	'libstdc++.so.6',
]

pub struct LinuxInstallRequest {
pub:
	prefix                string
	system_ld_so          string
	preferred_gcc_formula string = 'gcc'
	intel                 bool
	is_64_bit             bool
	arm                   bool
	ppc64le               bool
}

pub struct LinuxGccSetupResult {
pub:
	gcc_available         bool
	glibc_installed       bool
	configuration_written bool
	ldconfig_ran          bool
	removed_links         []string
	created_links         []string
}

pub struct LinuxInstallHookResult {
pub:
	super_called bool
	all_fatal    bool
	ld_so_linked bool
	gcc_setup    LinuxGccSetupResult
}

pub fn linux_cpu_error(cpu LinuxInstallRequest) ?string {
	if (cpu.intel && cpu.is_64_bit) || cpu.arm {
		return none
	}
	mut message := "Sorry, Homebrew does not support your computer's CPU architecture!"
	if cpu.ppc64le {
		message += '\nFor OpenPOWER Linux (PPC64LE) support, see:\n  https://github.com/homebrew-ppc64le/brew\n'
	}
	return message
}

pub fn check_linux_cpu(cpu LinuxInstallRequest) ! {
	if message := linux_cpu_error(cpu) {
		return error(message)
	}
}

fn linux_install_link_matches(path string, target string) bool {
	if !os.is_readable(path) || !os.is_link(path) {
		return false
	}
	return (os.readlink(path) or { return false }) == target
}

fn linux_install_force_symlink(target string, link string) ! {
	if os.exists(link) || os.is_link(link) {
		os.rm(link)!
	}
	os.symlink(target, link)!
}

pub fn symlink_linux_ld_so(request LinuxInstallRequest) !bool {
	brew_ld_so := os.join_path(request.prefix, 'lib', 'ld.so')
	glibc_ld_so := os.join_path(request.prefix, 'opt', 'glibc', 'bin', 'ld.so')
	ld_so := if os.is_readable(glibc_ld_so) { glibc_ld_so } else { request.system_ld_so }
	if ld_so == '' {
		if os.is_readable(brew_ld_so) {
			return false
		}
		return error("Unable to locate the system's dynamic linker")
	}
	if linux_install_link_matches(brew_ld_so, ld_so) {
		return false
	}
	os.mkdir_all(os.join_path(request.prefix, 'lib'))!
	linux_install_force_symlink(ld_so, brew_ld_so)!
	return true
}

pub fn setup_linux_preferred_gcc_libs(request LinuxInstallRequest) !LinuxGccSetupResult {
	gcc_formula := if request.preferred_gcc_formula == '' {
		'gcc'
	} else {
		request.preferred_gcc_formula
	}
	gcc_opt_prefix := os.join_path(request.prefix, 'opt', gcc_formula)
	glibc_ld_so := os.join_path(request.prefix, 'opt', 'glibc', 'bin', 'ld.so')
	glibc_installed := os.is_readable(glibc_ld_so)
	if !os.is_readable(gcc_opt_prefix) {
		return LinuxGccSetupResult{
			glibc_installed: glibc_installed
		}
	}
	mut configuration_written := false
	mut ldconfig_ran := false
	mut removed_links := []string{}
	mut created_links := []string{}
	if glibc_installed {
		ld_so_conf_d := os.join_path(request.prefix, 'etc', 'ld.so.conf.d')
		if !os.exists(ld_so_conf_d) {
			os.mkdir_all(ld_so_conf_d)!
			os.chmod(ld_so_conf_d, 0o755)!
		}
		ld_gcc_conf := os.join_path(ld_so_conf_d, '50-homebrew-preferred-gcc.conf')
		ld_gcc_conf_content := '# This file is generated by Homebrew. Do not modify.\n${os.join_path(gcc_opt_prefix, 'lib', 'gcc', 'current')}\n'
		current_content := os.read_file(ld_gcc_conf) or { '' }
		if !os.exists(ld_gcc_conf) || current_content != ld_gcc_conf_content {
			ruby.atomic_write_file(ld_gcc_conf, ld_gcc_conf_content)!
			os.chmod(ld_gcc_conf, 0o600)!
			cache := os.join_path(request.prefix, 'etc', 'ld.so.cache')
			if os.exists(cache) || os.is_link(cache) {
				os.rm(cache)!
			}
			ldconfig := os.join_path(request.prefix, 'opt', 'glibc', 'sbin', 'ldconfig')
			_ = ruby.run_command(ldconfig, [])
			configuration_written = true
			ldconfig_ran = true
		}
	} else if !os.is_readable(os.join_path(request.prefix, 'lib')) {
		return error('${request.prefix}/lib does not exist!')
	}
	for library in install_gcc_runtime_libs {
		gcc_library_symlink := os.join_path(request.prefix, 'lib', library)
		if glibc_installed {
			if os.is_link(gcc_library_symlink) {
				os.rm(gcc_library_symlink)!
				removed_links << gcc_library_symlink
			}
			continue
		}
		gcc_library := os.join_path(gcc_opt_prefix, 'lib', 'gcc', 'current', library)
		if !os.is_readable(gcc_library)
			|| linux_install_link_matches(gcc_library_symlink, gcc_library) {
			continue
		}
		linux_install_force_symlink(gcc_library, gcc_library_symlink)!
		created_links << gcc_library_symlink
	}
	return LinuxGccSetupResult{
		gcc_available: true
		glibc_installed: glibc_installed
		configuration_written: configuration_written
		ldconfig_ran: ldconfig_ran
		removed_links: removed_links
		created_links: created_links
	}
}

pub fn run_linux_install_hook(request LinuxInstallRequest,
	all_fatal bool) !LinuxInstallHookResult {
	linked := symlink_linux_ld_so(request)!
	setup := setup_linux_preferred_gcc_libs(request)!
	return LinuxInstallHookResult{
		super_called: true
		all_fatal: all_fatal
		ld_so_linked: linked
		gcc_setup: setup
	}
}

fn linux_install_request_from_value(value ruby.Value) LinuxInstallRequest {
	return LinuxInstallRequest{
		prefix: value.attributes['prefix']
		system_ld_so: value.attributes['system_ld_so']
		preferred_gcc_formula: value.attributes['preferred_gcc_formula']
		intel: value.attributes['intel'] == 'true'
		is_64_bit: value.attributes['is_64_bit'] == 'true'
		arm: value.attributes['arm'] == 'true'
		ppc64le: value.attributes['ppc64le'] == 'true'
	}
}

fn linux_install_request(args []ruby.Value) LinuxInstallRequest {
	if args.len == 0 {
		return LinuxInstallRequest{
			prefix: ruby.environment_value('HOMEBREW_PREFIX')
		}
	}
	if args[0].attributes.len > 0 {
		return linux_install_request_from_value(args[0])
	}
	return LinuxInstallRequest{
		prefix: args[0].as_string()
		system_ld_so: if args.len > 1 { args[1].as_string() } else { '' }
	}
}

fn linux_install_hook_value(result LinuxInstallHookResult) ruby.Value {
	return ruby.structured_value('LinuxInstallHookResult', 'Linux install hooks complete', {
		'super_called':          result.super_called.str()
		'all_fatal':             result.all_fatal.str()
		'ld_so_linked':          result.ld_so_linked.str()
		'gcc_available':         result.gcc_setup.gcc_available.str()
		'configuration_written': result.gcc_setup.configuration_written.str()
		'ldconfig_ran':          result.gcc_setup.ldconfig_ran.str()
		'removed_links':         result.gcc_setup.removed_links.join(',')
		'created_links':         result.gcc_setup.created_links.join(',')
	})
}

fn linux_gcc_setup_value(result LinuxGccSetupResult) ruby.Value {
	return ruby.structured_value('LinuxGccSetupResult', 'GCC runtime libraries configured', {
		'gcc_available':         result.gcc_available.str()
		'glibc_installed':       result.glibc_installed.str()
		'configuration_written': result.configuration_written.str()
		'ldconfig_ran':          result.ldconfig_ran.str()
		'removed_links':         result.removed_links.join(',')
		'created_links':         result.created_links.join(',')
	})
}
