module linux

import brew_runtime

// Translated from Homebrew/brew `extend/os/linux/install.rb`.
// The original source is retained below until every stub has a typed V body.

// Ruby method `perform_preinstall_checks(all_fatal: false)` at line 24.
pub fn ruby_install_l24_d1_perform_preinstall_checks(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('perform_preinstall_checks', ...args)
}

// Ruby method `global_post_install` at line 31.
pub fn ruby_install_l31_d2_global_post_install(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('global_post_install', ...args)
}

// Ruby method `check_cpu` at line 38.
pub fn ruby_install_l38_d3_check_cpu(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('check_cpu', ...args)
}

// Ruby method `symlink_ld_so` at line 53.
pub fn ruby_install_l53_d4_symlink_ld_so(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('symlink_ld_so', ...args)
}

// Ruby method `setup_preferred_gcc_libs` at line 73.
pub fn ruby_install_l73_d5_setup_preferred_gcc_libs(args ...brew_runtime.Value) brew_runtime.Value {
	return brew_runtime.unimplemented_fn('setup_preferred_gcc_libs', ...args)
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "os/linux/ld"
// 5: require "os/linux/libstdcxx"
// 6: require "utils/output"
// 7:
// 8: module OS
// 9:   module Linux
// 10:     module Install
// 11:       module ClassMethods
// 12:         # We link GCC runtime libraries that are not specifically used for Fortran,
// 13:         # which are linked by the GCC formula. We only use the versioned shared libraries
// 14:         # as the other shared and static libraries are only used at build time where
// 15:         # GCC can find its own libraries.
// 16:         GCC_RUNTIME_LIBS = %W[
// 17:           libatomic.so.1
// 18:           libgcc_s.so.1
// 19:           libgomp.so.1
// 20:           #{OS::Linux::Libstdcxx::SONAME}
// 21:         ].freeze
// 22:
// 23:         sig { params(all_fatal: T::Boolean).void }
// 24:         def perform_preinstall_checks(all_fatal: false)
// 25:           super
// 26:           symlink_ld_so
// 27:           setup_preferred_gcc_libs
// 28:         end
// 29:
// 30:         sig { void }
// 31:         def global_post_install
// 32:           super
// 33:           symlink_ld_so
// 34:           setup_preferred_gcc_libs
// 35:         end
// 36:
// 37:         sig { void }
// 38:         def check_cpu
// 39:           return if ::Hardware::CPU.intel? && ::Hardware::CPU.is_64_bit?
// 40:           return if ::Hardware::CPU.arm?
// 41:
// 42:           message = "Sorry, Homebrew does not support your computer's CPU architecture!"
// 43:           if ::Hardware::CPU.ppc64le?
// 44:             message += <<~EOS
// 45:               For OpenPOWER Linux (PPC64LE) support, see:
// 46:                 #{Formatter.url("https://github.com/homebrew-ppc64le/brew")}
// 47:             EOS
// 48:           end
// 49:           ::Kernel.abort message
// 50:         end
// 51:
// 52:         sig { void }
// 53:         def symlink_ld_so
// 54:           brew_ld_so = HOMEBREW_PREFIX/"lib/ld.so"
// 55:
// 56:           ld_so = HOMEBREW_PREFIX/"opt/glibc/bin/ld.so"
// 57:           unless ld_so.readable?
// 58:             ld_so = OS::Linux::Ld.system_ld_so
// 59:             if ld_so.blank?
// 60:               ::Kernel.raise "Unable to locate the system's dynamic linker" unless brew_ld_so.readable?
// 61:
// 62:               return
// 63:             end
// 64:           end
// 65:
// 66:           return if brew_ld_so.readable? && (brew_ld_so.readlink == ld_so)
// 67:
// 68:           FileUtils.mkdir_p HOMEBREW_PREFIX/"lib"
// 69:           FileUtils.ln_sf ld_so, brew_ld_so
// 70:         end
// 71:
// 72:         sig { void }
// 73:         def setup_preferred_gcc_libs
// 74:           gcc_opt_prefix = HOMEBREW_PREFIX/"opt/#{OS::LINUX_PREFERRED_GCC_RUNTIME_FORMULA}"
// 75:           glibc_installed = (HOMEBREW_PREFIX/"opt/glibc/bin/ld.so").readable?
// 76:
// 77:           return unless gcc_opt_prefix.readable?
// 78:
// 79:           if glibc_installed
// 80:             ld_so_conf_d = HOMEBREW_PREFIX/"etc/ld.so.conf.d"
// 81:             unless ld_so_conf_d.exist?
// 82:               ld_so_conf_d.mkpath
// 83:               FileUtils.chmod "go-w", ld_so_conf_d
// 84:             end
// 85:
// 86:             # Add gcc to ld search paths
// 87:             ld_gcc_conf = ld_so_conf_d/"50-homebrew-preferred-gcc.conf"
// 88:             ld_gcc_conf_content = <<~EOS
// 89:               # This file is generated by Homebrew. Do not modify.
// 90:               #{gcc_opt_prefix}/lib/gcc/current
// 91:             EOS
// 92:
// 93:             if !ld_gcc_conf.exist? || (ld_gcc_conf.read != ld_gcc_conf_content)
// 94:               ld_gcc_conf.atomic_write ld_gcc_conf_content
// 95:               FileUtils.chmod "u=rw,go-wx", ld_gcc_conf
// 96:
// 97:               FileUtils.rm_f HOMEBREW_PREFIX/"etc/ld.so.cache"
// 98:               ::Kernel.system HOMEBREW_PREFIX/"opt/glibc/sbin/ldconfig"
// 99:             end
// 100:           else
// 101:             Utils::Output.odie "#{HOMEBREW_PREFIX}/lib does not exist!" unless (HOMEBREW_PREFIX/"lib").readable?
// 102:           end
// 103:
// 104:           GCC_RUNTIME_LIBS.each do |library|
// 105:             gcc_library_symlink = HOMEBREW_PREFIX/"lib/#{library}"
// 106:
// 107:             if glibc_installed
// 108:               # Remove legacy symlinks
// 109:               FileUtils.rm gcc_library_symlink if gcc_library_symlink.symlink?
// 110:             else
// 111:               gcc_library = gcc_opt_prefix/"lib/gcc/current/#{library}"
// 112:               # Skip if the link target doesn't exist.
// 113:               next unless gcc_library.readable?
// 114:
// 115:               # Also skip if the symlink already exists.
// 116:               next if gcc_library_symlink.readable? && (gcc_library_symlink.readlink == gcc_library)
// 117:
// 118:               FileUtils.ln_sf gcc_library, gcc_library_symlink
// 119:             end
// 120:           end
// 121:         end
// 122:       end
// 123:     end
// 124:   end
// 125: end
// 126:
// 127: Homebrew::Install.singleton_class.prepend(OS::Linux::Install::ClassMethods)
