module linux

import ruby
import os

// Translated from Homebrew/brew `extend/os/linux/install.rb`.
// The original source is retained below until every stub has a typed V body.

pub const install_gcc_runtime_libs = [
	'libatomic.so.1',
	'libgcc_s.so.1',
	'libgomp.so.1',
	'libstdc++.so.6',
]

pub struct LinuxInstallRequest {
pub:
	prefix                string
	system_ld_so          string
	preferred_gcc_formula string = 'gcc'
	intel                 bool
	is_64_bit             bool
	arm                   bool
	ppc64le               bool
}

pub struct LinuxGccSetupResult {
pub:
	gcc_available         bool
	glibc_installed       bool
	configuration_written bool
	ldconfig_ran          bool
	removed_links         []string
	created_links         []string
}

pub struct LinuxInstallHookResult {
pub:
	super_called bool
	all_fatal    bool
	ld_so_linked bool
	gcc_setup    LinuxGccSetupResult
}

pub fn linux_cpu_error(cpu LinuxInstallRequest) ?string {
	if (cpu.intel && cpu.is_64_bit) || cpu.arm {
		return none
	}
	mut message := "Sorry, Homebrew does not support your computer's CPU architecture!"
	if cpu.ppc64le {
		message += '\nFor OpenPOWER Linux (PPC64LE) support, see:\n  https://github.com/homebrew-ppc64le/brew\n'
	}
	return message
}

pub fn check_linux_cpu(cpu LinuxInstallRequest) ! {
	if message := linux_cpu_error(cpu) {
		return error(message)
	}
}

fn linux_install_link_matches(path string, target string) bool {
	if !os.is_readable(path) || !os.is_link(path) {
		return false
	}
	return (os.readlink(path) or { return false }) == target
}

fn linux_install_force_symlink(target string, link string) ! {
	if os.exists(link) || os.is_link(link) {
		os.rm(link)!
	}
	os.symlink(target, link)!
}

pub fn symlink_linux_ld_so(request LinuxInstallRequest) !bool {
	brew_ld_so := os.join_path(request.prefix, 'lib', 'ld.so')
	glibc_ld_so := os.join_path(request.prefix, 'opt', 'glibc', 'bin', 'ld.so')
	ld_so := if os.is_readable(glibc_ld_so) { glibc_ld_so } else { request.system_ld_so }
	if ld_so == '' {
		if os.is_readable(brew_ld_so) {
			return false
		}
		return error("Unable to locate the system's dynamic linker")
	}
	if linux_install_link_matches(brew_ld_so, ld_so) {
		return false
	}
	os.mkdir_all(os.join_path(request.prefix, 'lib'))!
	linux_install_force_symlink(ld_so, brew_ld_so)!
	return true
}

pub fn setup_linux_preferred_gcc_libs(request LinuxInstallRequest) !LinuxGccSetupResult {
	gcc_formula := if request.preferred_gcc_formula == '' {
		'gcc'
	} else {
		request.preferred_gcc_formula
	}
	gcc_opt_prefix := os.join_path(request.prefix, 'opt', gcc_formula)
	glibc_ld_so := os.join_path(request.prefix, 'opt', 'glibc', 'bin', 'ld.so')
	glibc_installed := os.is_readable(glibc_ld_so)
	if !os.is_readable(gcc_opt_prefix) {
		return LinuxGccSetupResult{
			glibc_installed: glibc_installed
		}
	}
	mut configuration_written := false
	mut ldconfig_ran := false
	mut removed_links := []string{}
	mut created_links := []string{}
	if glibc_installed {
		ld_so_conf_d := os.join_path(request.prefix, 'etc', 'ld.so.conf.d')
		if !os.exists(ld_so_conf_d) {
			os.mkdir_all(ld_so_conf_d)!
			os.chmod(ld_so_conf_d, 0o755)!
		}
		ld_gcc_conf := os.join_path(ld_so_conf_d, '50-homebrew-preferred-gcc.conf')
		ld_gcc_conf_content := '# This file is generated by Homebrew. Do not modify.\n${os.join_path(gcc_opt_prefix, 'lib', 'gcc', 'current')}\n'
		current_content := os.read_file(ld_gcc_conf) or { '' }
		if !os.exists(ld_gcc_conf) || current_content != ld_gcc_conf_content {
			ruby.atomic_write_file(ld_gcc_conf, ld_gcc_conf_content)!
			os.chmod(ld_gcc_conf, 0o600)!
			cache := os.join_path(request.prefix, 'etc', 'ld.so.cache')
			if os.exists(cache) || os.is_link(cache) {
				os.rm(cache)!
			}
			ldconfig := os.join_path(request.prefix, 'opt', 'glibc', 'sbin', 'ldconfig')
			_ = ruby.run_command(ldconfig, [])
			configuration_written = true
			ldconfig_ran = true
		}
	} else if !os.is_readable(os.join_path(request.prefix, 'lib')) {
		return error('${request.prefix}/lib does not exist!')
	}
	for library in install_gcc_runtime_libs {
		gcc_library_symlink := os.join_path(request.prefix, 'lib', library)
		if glibc_installed {
			if os.is_link(gcc_library_symlink) {
				os.rm(gcc_library_symlink)!
				removed_links << gcc_library_symlink
			}
			continue
		}
		gcc_library := os.join_path(gcc_opt_prefix, 'lib', 'gcc', 'current', library)
		if !os.is_readable(gcc_library)
			|| linux_install_link_matches(gcc_library_symlink, gcc_library) {
			continue
		}
		linux_install_force_symlink(gcc_library, gcc_library_symlink)!
		created_links << gcc_library_symlink
	}
	return LinuxGccSetupResult{
		gcc_available: true
		glibc_installed: glibc_installed
		configuration_written: configuration_written
		ldconfig_ran: ldconfig_ran
		removed_links: removed_links
		created_links: created_links
	}
}

pub fn run_linux_install_hook(request LinuxInstallRequest,
	all_fatal bool) !LinuxInstallHookResult {
	linked := symlink_linux_ld_so(request)!
	setup := setup_linux_preferred_gcc_libs(request)!
	return LinuxInstallHookResult{
		super_called: true
		all_fatal: all_fatal
		ld_so_linked: linked
		gcc_setup: setup
	}
}

fn linux_install_request_from_value(value ruby.Value) LinuxInstallRequest {
	return LinuxInstallRequest{
		prefix: value.attributes['prefix']
		system_ld_so: value.attributes['system_ld_so']
		preferred_gcc_formula: value.attributes['preferred_gcc_formula']
		intel: value.attributes['intel'] == 'true'
		is_64_bit: value.attributes['is_64_bit'] == 'true'
		arm: value.attributes['arm'] == 'true'
		ppc64le: value.attributes['ppc64le'] == 'true'
	}
}

fn linux_install_request(args []ruby.Value) LinuxInstallRequest {
	if args.len == 0 {
		return LinuxInstallRequest{
			prefix: ruby.environment_value('HOMEBREW_PREFIX')
		}
	}
	if args[0].attributes.len > 0 {
		return linux_install_request_from_value(args[0])
	}
	return LinuxInstallRequest{
		prefix: args[0].as_string()
		system_ld_so: if args.len > 1 { args[1].as_string() } else { '' }
	}
}

fn linux_install_hook_value(result LinuxInstallHookResult) ruby.Value {
	return ruby.structured_value('LinuxInstallHookResult', 'Linux install hooks complete', {
		'super_called':          result.super_called.str()
		'all_fatal':             result.all_fatal.str()
		'ld_so_linked':          result.ld_so_linked.str()
		'gcc_available':         result.gcc_setup.gcc_available.str()
		'configuration_written': result.gcc_setup.configuration_written.str()
		'ldconfig_ran':          result.gcc_setup.ldconfig_ran.str()
		'removed_links':         result.gcc_setup.removed_links.join(',')
		'created_links':         result.gcc_setup.created_links.join(',')
	})
}

fn linux_gcc_setup_value(result LinuxGccSetupResult) ruby.Value {
	return ruby.structured_value('LinuxGccSetupResult', 'GCC runtime libraries configured', {
		'gcc_available':         result.gcc_available.str()
		'glibc_installed':       result.glibc_installed.str()
		'configuration_written': result.configuration_written.str()
		'ldconfig_ran':          result.ldconfig_ran.str()
		'removed_links':         result.removed_links.join(',')
		'created_links':         result.created_links.join(',')
	})
}

// Ruby method `perform_preinstall_checks(all_fatal: false)` at line 24.
pub fn ruby_install_l24_d1_perform_preinstall_checks(args ...ruby.Value) ruby.Value {
	request := linux_install_request(args)
	all_fatal := args.len > 1 && (args[1].as_bool() or { false })
	return linux_install_hook_value(run_linux_install_hook(request, all_fatal) or { panic(err) })
}

// Ruby method `global_post_install` at line 31.
pub fn ruby_install_l31_d2_global_post_install(args ...ruby.Value) ruby.Value {
	return linux_install_hook_value(run_linux_install_hook(linux_install_request(args), false) or {
		panic(err)
	})
}

// Ruby method `check_cpu` at line 38.
pub fn ruby_install_l38_d3_check_cpu(args ...ruby.Value) ruby.Value {
	mut request := linux_install_request(args)
	if args.len > 0 && args[0].attributes.len == 0 {
		request = LinuxInstallRequest{
			intel: args[0].as_bool() or { false }
			is_64_bit: args.len > 1 && (args[1].as_bool() or { false })
			arm: args.len > 2 && (args[2].as_bool() or { false })
			ppc64le: args.len > 3 && (args[3].as_bool() or { false })
		}
	}
	check_linux_cpu(request) or { panic(err) }
	return ruby.object_value('NilClass', 'nil')
}

// Ruby method `symlink_ld_so` at line 53.
pub fn ruby_install_l53_d4_symlink_ld_so(args ...ruby.Value) ruby.Value {
	return ruby.bool_value(symlink_linux_ld_so(linux_install_request(args)) or {
		panic(err)
	})
}

// Ruby method `setup_preferred_gcc_libs` at line 73.
pub fn ruby_install_l73_d5_setup_preferred_gcc_libs(args ...ruby.Value) ruby.Value {
	return linux_gcc_setup_value(setup_linux_preferred_gcc_libs(linux_install_request(args)) or {
		panic(err)
	})
}

// Original Ruby source (line-for-line):
// 1: # typed: strict
// 2: # frozen_string_literal: true
// 3:
// 4: require "os/linux/ld"
// 5: require "os/linux/libstdcxx"
// 6: require "utils/output"
// 7:
// 8: module OS
// 9:   module Linux
// 10:     module Install
// 11:       module ClassMethods
// 12:         # We link GCC runtime libraries that are not specifically used for Fortran,
// 13:         # which are linked by the GCC formula. We only use the versioned shared libraries
// 14:         # as the other shared and static libraries are only used at build time where
// 15:         # GCC can find its own libraries.
// 16:         GCC_RUNTIME_LIBS = %W[
// 17:           libatomic.so.1
// 18:           libgcc_s.so.1
// 19:           libgomp.so.1
// 20:           #{OS::Linux::Libstdcxx::SONAME}
// 21:         ].freeze
// 22:
// 23:         sig { params(all_fatal: T::Boolean).void }
// 24:         def perform_preinstall_checks(all_fatal: false)
// 25:           super
// 26:           symlink_ld_so
// 27:           setup_preferred_gcc_libs
// 28:         end
// 29:
// 30:         sig { void }
// 31:         def global_post_install
// 32:           super
// 33:           symlink_ld_so
// 34:           setup_preferred_gcc_libs
// 35:         end
// 36:
// 37:         sig { void }
// 38:         def check_cpu
// 39:           return if ::Hardware::CPU.intel? && ::Hardware::CPU.is_64_bit?
// 40:           return if ::Hardware::CPU.arm?
// 41:
// 42:           message = "Sorry, Homebrew does not support your computer's CPU architecture!"
// 43:           if ::Hardware::CPU.ppc64le?
// 44:             message += <<~EOS
// 45:               For OpenPOWER Linux (PPC64LE) support, see:
// 46:                 #{Formatter.url("https://github.com/homebrew-ppc64le/brew")}
// 47:             EOS
// 48:           end
// 49:           ::Kernel.abort message
// 50:         end
// 51:
// 52:         sig { void }
// 53:         def symlink_ld_so
// 54:           brew_ld_so = HOMEBREW_PREFIX/"lib/ld.so"
// 55:
// 56:           ld_so = HOMEBREW_PREFIX/"opt/glibc/bin/ld.so"
// 57:           unless ld_so.readable?
// 58:             ld_so = OS::Linux::Ld.system_ld_so
// 59:             if ld_so.blank?
// 60:               ::Kernel.raise "Unable to locate the system's dynamic linker" unless brew_ld_so.readable?
// 61:
// 62:               return
// 63:             end
// 64:           end
// 65:
// 66:           return if brew_ld_so.readable? && (brew_ld_so.readlink == ld_so)
// 67:
// 68:           FileUtils.mkdir_p HOMEBREW_PREFIX/"lib"
// 69:           FileUtils.ln_sf ld_so, brew_ld_so
// 70:         end
// 71:
// 72:         sig { void }
// 73:         def setup_preferred_gcc_libs
// 74:           gcc_opt_prefix = HOMEBREW_PREFIX/"opt/#{OS::LINUX_PREFERRED_GCC_RUNTIME_FORMULA}"
// 75:           glibc_installed = (HOMEBREW_PREFIX/"opt/glibc/bin/ld.so").readable?
// 76:
// 77:           return unless gcc_opt_prefix.readable?
// 78:
// 79:           if glibc_installed
// 80:             ld_so_conf_d = HOMEBREW_PREFIX/"etc/ld.so.conf.d"
// 81:             unless ld_so_conf_d.exist?
// 82:               ld_so_conf_d.mkpath
// 83:               FileUtils.chmod "go-w", ld_so_conf_d
// 84:             end
// 85:
// 86:             # Add gcc to ld search paths
// 87:             ld_gcc_conf = ld_so_conf_d/"50-homebrew-preferred-gcc.conf"
// 88:             ld_gcc_conf_content = <<~EOS
// 89:               # This file is generated by Homebrew. Do not modify.
// 90:               #{gcc_opt_prefix}/lib/gcc/current
// 91:             EOS
// 92:
// 93:             if !ld_gcc_conf.exist? || (ld_gcc_conf.read != ld_gcc_conf_content)
// 94:               ld_gcc_conf.atomic_write ld_gcc_conf_content
// 95:               FileUtils.chmod "u=rw,go-wx", ld_gcc_conf
// 96:
// 97:               FileUtils.rm_f HOMEBREW_PREFIX/"etc/ld.so.cache"
// 98:               ::Kernel.system HOMEBREW_PREFIX/"opt/glibc/sbin/ldconfig"
// 99:             end
// 100:           else
// 101:             Utils::Output.odie "#{HOMEBREW_PREFIX}/lib does not exist!" unless (HOMEBREW_PREFIX/"lib").readable?
// 102:           end
// 103:
// 104:           GCC_RUNTIME_LIBS.each do |library|
// 105:             gcc_library_symlink = HOMEBREW_PREFIX/"lib/#{library}"
// 106:
// 107:             if glibc_installed
// 108:               # Remove legacy symlinks
// 109:               FileUtils.rm gcc_library_symlink if gcc_library_symlink.symlink?
// 110:             else
// 111:               gcc_library = gcc_opt_prefix/"lib/gcc/current/#{library}"
// 112:               # Skip if the link target doesn't exist.
// 113:               next unless gcc_library.readable?
// 114:
// 115:               # Also skip if the symlink already exists.
// 116:               next if gcc_library_symlink.readable? && (gcc_library_symlink.readlink == gcc_library)
// 117:
// 118:               FileUtils.ln_sf gcc_library, gcc_library_symlink
// 119:             end
// 120:           end
// 121:         end
// 122:       end
// 123:     end
// 124:   end
// 125: end
// 126:
// 127: Homebrew::Install.singleton_class.prepend(OS::Linux::Install::ClassMethods)
